### ISSUE TITLE
grant is missing from session when server restarted 

### ISSUE THREAD

**Issue by hkghatsuki** [panva/node-oidc-provider#1087]
### What happened?
I am able to get the access tokens at the first, but after the server restarted, I am unable to connect to the server again until the cookies are removed or the session record is deleted in database. The program thrown exception is about the grant data is undefined

### Version

7.6.0

### Node.js version

14.16.1

### Reproduction & Logs

TypeError: Cannot read property 'getOIDCScopeEncountered' of undefined
    at Check.oidc.oidc (C:\nodejs\itoc\oidc\node_modules\oidc-provider\lib\helpers\interaction_policy\prompts\consent.js:31:50)
    at C:\nodejs\itoc\oidc\node_modules\oidc-provider\lib\actions\authorization\interactions.js:23:17
    at Array.map (<anonymous>)
    at interactions (C:\nodejs\itoc\oidc\node_modules\oidc-provider\lib\actions\authorization\interactions.js:20:50)
    at async parseBodyIfPost (C:\nodejs\itoc\oidc\node_modules\oidc-provider\lib\shared\conditional_body.js:7:5)
    at async sessionHandler (C:\nodejs\itoc\oidc\node_modules\oidc-provider\lib\shared\session.js:29:5)
    at async noCache (C:\nodejs\itoc\oidc\node_modules\oidc-provider\lib\shared\no_cache.js:4:3)
    at async authorizationErrorHandler (C:\nodejs\itoc\oidc\node_modules\oidc-provider\lib\shared\authorization_error_handler.js:53:7)
    at async ensureSessionSave (C:\nodejs\itoc\oidc\node_modules\oidc-provider\lib\helpers\initialize_app.js:50:7)
    at async contextEnsureOidc (C:\nodejs\itoc\oidc\node_modules\oidc-provider\lib\shared\context_ensure_oidc.js:4:5)

### 

- [x] I have provided a gist or a public repo which can be cloned, installed and ran locally in order to reproduce the bug in the textarea above.
- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/node-oidc-provider/blob/main/CODE_OF_CONDUCT.md)

**Comment by hkghatsuki** [comment]
I am sorry that's a problem on unable to find account from database
