### ISSUE TITLE
Error when initializing oidc-provider

### ISSUE THREAD

**Issue by Lilleri** [panva/node-oidc-provider#1137]
### What happened?

I install the the software through npm with this command
npm install oidc-provider --save,
when i set the require library

 const { Provider } = require('oidc-provider');

i receive this error:

 /usr/src/app/node_modules/oidc-provider/lib/provider.js:86
   #AccessToken;
   ^
 
 SyntaxError: Invalid or unexpected token
     at new Script (vm.js:79:7)
     at createScript (vm.js:251:10)
     at Object.runInThisContext (vm.js:303:10)
     at Module._compile (internal/modules/cjs/loader.js:656:28)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
     at Module.load (internal/modules/cjs/loader.js:598:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
     at Module.require (internal/modules/cjs/loader.js:636:17)
     at require (internal/modules/cjs/helpers.js:20:18)
what can i do?

### Version

7.9.0

### Node.js version

10.13

### Reproduction & Logs

/usr/src/app/node_modules/oidc-provider/lib/provider.js:86
   #AccessToken;
   ^
 
 SyntaxError: Invalid or unexpected token
     at new Script (vm.js:79:7)
     at createScript (vm.js:251:10)
     at Object.runInThisContext (vm.js:303:10)
     at Module._compile (internal/modules/cjs/loader.js:656:28)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
     at Module.load (internal/modules/cjs/loader.js:598:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
     at Module.require (internal/modules/cjs/loader.js:636:17)
     at require (internal/modules/cjs/helpers.js:20:18)

### 

- [X] I have provided a gist or a public repo which can be cloned, installed and ran locally in order to reproduce the bug in the textarea above.
- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/node-oidc-provider/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Node.js 10 is not a supported runtime.

**Comment by Lilleri** [comment]
thanks for the reply! I cannot find this information in the documentation, so which version should i use?

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/v7.x/package.json#L109-L111
