### ISSUE TITLE
MongoError: E11000 duplicate key error collection: oidc.session index: payload.uid_1

### ISSUE THREAD

**Issue by EdouardPauw** [panva/node-oidc-provider#1145]
### What happened?

Hello,

I noticied that a MongoError: E11000 is raised by the provider during autorization code flow.
After long investigation I succeeded to reproduce it and it seems to appear when 2 concurent authorization call are made.

I supposed it could be from our configuration and prompt policy so I simplified it using your example (https://github.com/panva/node-oidc-provider/tree/main/example) but I still got the issue.

So it seems that the provider is trying to create an other session with the same "payload.uid" but I dont know why. Shoud not it update the existing one ? Do you have any idea how to resolve this ?

### Version

7.6.1

### Node.js version

v14.15.4

### Reproduction & Logs

In order to reproduce the issue you must have 2 differents clients (RP).

**Steps to reproduce the behaviour**
_All of the steps are made in the same browser_
- First make an authorization request using the first client and authenticate as a user in order to receive the code from the provider
- At this point a session should be open 
![step1_session](https://user-images.githubusercontent.com/74250819/140961713-b3566760-b891-42b2-8110-6ccd1126662a.png)
 - Make 2 simultaneous authorization call using the second client (programmatically or the error is not alwais raised)
 - One of them may succeed and the other one fail

**Logs**
```
oidc-provider:server_error path=/auth/W1z3dFsi2UcFQ3z0HVhiO method=GET error=MongoError: E11000 duplicate key error collection: oidc.session index: payload.uid_1 dup key: { payload.uid: "Wa615om1fZyh9dWwrXFkQ" } at Function.create (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/core/error.js:59:12) at toError (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/utils.js:130:22) at /home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/operations/common_functions.js:384:39 at handler (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/core/sdam/topology.js:961:24) at /home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/cmap/connection_pool.js:352:13 at handleOperationResult (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/core/sdam/server.js:567:5) at MessageStream.messageHandler (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/cmap/connection.js:308:5)     at MessageStream.emit (events.js:315:20)     at MessageStream.EventEmitter.emit (domain.js:467:12) at processIncomingData (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/cmap/message_stream.js:144:12) { driver: true, index: 0, code: 11000, keyPattern: { 'payload.uid': 1 }, keyValue: { 'payload.uid': 'Wa615om1fZyh9dWwrXFkQ' } } +57m
  oidc-provider:server_error:trace MongoError: E11000 duplicate key error collection: oidc.session index: payload.uid_1 dup key: { payload.uid: "Wa615om1fZyh9dWwrXFkQ" }
  oidc-provider:server_error:trace     at Function.create (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/core/error.js:59:12)
  oidc-provider:server_error:trace     at toError (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/utils.js:130:22)
  oidc-provider:server_error:trace     at /home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/operations/common_functions.js:384:39
  oidc-provider:server_error:trace     at handler (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/core/sdam/topology.js:961:24)
  oidc-provider:server_error:trace     at /home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/cmap/connection_pool.js:352:13
  oidc-provider:server_error:trace     at handleOperationResult (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/core/sdam/server.js:567:5)
  oidc-provider:server_error:trace     at MessageStream.messageHandler (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/cmap/connection.js:308:5)
  oidc-provider:server_error:trace     at MessageStream.emit (events.js:315:20)
  oidc-provider:server_error:trace     at MessageStream.EventEmitter.emit (domain.js:467:12)
  oidc-provider:server_error:trace     at processIncomingData (/home/developer/Documents/Projet/Sodexo/sodexo-connect-oidc-provider/node_modules/mongodb/lib/cmap/message_stream.js:144:12) +57m
```

**Configuration**
```
{
        adapter,
        acrValues: mainConfiguration.acrPolicies.map((acrPolicy) => acrPolicy.acrValue),
        clientDefaults: {
          default_acr_values: ['F'],
          id_token_signed_response_alg: 'ES256',
          pkceRequired: true,
        },
        claims: {
          sid: null,
          openid: ['sub', 'realm'],
          email: ['email'],
          phone: ['phone_number'],
          address: ['address'],
          profile: ['gender', 'given_name', 'family_name', 'middle_name', 'birthdate', 'locale'],
        },
        scopes: mainConfiguration.scopePolicies.map((scope) => scope.scope),
        clients: getClients(),
        jwks: {
          keys: [
            {
              crv: 'P-256',
              d: 'xxxxxxxxxxxxxxxxxxxxxxxx',
              kty: 'EC',
              x: 'xxxxxxxxxxxxxxxxxxxxxxxx,
              y: 'xxxxxxxxxxxxxxxxxxxxxxxx',
              kid: 'test-key',
            },
          ],
        },
        cookies: {
          names: {
            interaction: 'op_interaction',
            resume: 'op_interaction_resume',
            session: 'op_session',
            state: 'op_state',
          },
          long: {
            httpOnly: true,
            overwrite: true,
            signed: true,
            secure: process.env.APP_ENV !== 'local',
            sameSite: 'lax',
            path: '/op',
          },
          short: {
            httpOnly: true,
            overwrite: true,
            signed: true,
            secure: process.env.APP_ENV !== 'local',
            sameSite: 'lax',
            path: '/op',
          },
          keys: mainConfiguration.cookieKeys,
        },
        interactions: OidcService.getInteractions(),
        routes: {
          authorization: '/auth',
          code_verification: '/device',
          device_authorization: '/device/auth',
          end_session: '/session/end',
          introspection: '/token/introspection',
          jwks: '/jwks',
          pushed_authorization_request: '/request',
          registration: '/reg',
          revocation: '/token/revocation',
          token: '/token',
          userinfo: '/me',
        },
        features: {
          backchannelLogout: { enabled: true, ack: 'draft-06' },
          clientCredentials: { enabled: true },
          devInteractions: { enabled: false },
          deviceFlow: { enabled: false },
          introspection: { enabled: true },
          revocation: { enabled: true },
          rpInitiatedLogout: {
            enabled: true,
            logoutSource: async (ctx, form) => {
              ctx.body = await logoutPage(ctx, form);
            },
            postLogoutSuccessSource: async (ctx) => {
              ctx.body = await postLogoutSuccessPage(ctx);
            },
          },
          userinfo: { enabled: true },
        },
        findAccount: (ctx, sub): any => AccountService.findAccount(ctx, sub),
        pkce: {
          methods: ['S256'],
          required: (ctx, client) => {
            return client.metadata().pkceRequired;
          },
        },
}
```

### 

- [X] I have provided a gist or a public repo which can be cloned, installed and ran locally in order to reproduce the bug in the textarea above.
- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/node-oidc-provider/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Sounds like the unique index is working to prevent concurrent data overwriting one another. I'm going to close this since the adapter is just an example.
