### ISSUE TITLE
Get "TypeError: this.res.removeHeader is not a function"

### ISSUE THREAD

**Issue by Lichtjaeger** [panva/node-oidc-provider#124]
Node v8.1.3
node-oidc-provider v1.15.3

Using it as `provider.callback` I get the following console output (with debug) by navigating to "/.well-known/webfinger".

```
PS D:\pscheler\Documents\Projekte\openID-Connect> node .
NOTICE: a draft/experimental feature (oauthNativeApps) enabled, future updates to this feature will be released as MINOR releases
  oidc-provider:server_error uuid=48ec5ecd-9fbc-4ffb-bf19-97b158868faa path=/.well-known/webfinger error=TypeError: this.res.removeHeader is not a function at Object.remove (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\koa\lib\response.js:478:14) at Object.set body [as body] (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\koa\lib\response.js:176:10) at Object.body (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\delegates\index.js:92:31) at Object.renderWebfingerResponse (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\oidc-provider\lib\actions\webfinger.js:5:15) at renderWebfingerResponse.next (<anonymous>) at onFulfilled (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:65:19) at D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:54:5 at Promise (<anonymous>) at Object.co (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:50:10) at Object.toPromise (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:118:63) at next (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:99:29) at onFulfilled (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:69:7) at D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:54:5 at Promise (<anonymous>) at Object.co (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:50:10) at Object.toPromise (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:118:63) at next (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:99:29) at onFulfilled (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:69:7) at D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:54:5 at Promise (<anonymous>) at Object.co (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:50:10) at Object.toPromise (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:118:63) at next (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:99:29) at onFulfilled (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:69:7) at D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:54:5 at Promise (<anonymous>) at Object.co (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:50:10) at Object.toPromise (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:118:63) at next (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:99:29) at onFulfilled (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:69:7) at D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:54:5 at Promise (<anonymous>) at Object.co (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:50:10) at Object.createPromise (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:30:15) +0ms
  oidc-provider:server_error:trace TypeError: this.res.removeHeader is not a function
  oidc-provider:server_error:trace     at Object.remove (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\koa\lib\response.js:478:14)
  oidc-provider:server_error:trace     at Object.set body [as body] (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\koa\lib\response.js:176:10)
  oidc-provider:server_error:trace     at Object.body (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\delegates\index.js:92:31)
  oidc-provider:server_error:trace     at Object.renderWebfingerResponse (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\oidc-provider\lib\actions\webfinger.js:5:15)
  oidc-provider:server_error:trace     at renderWebfingerResponse.next (<anonymous>)
  oidc-provider:server_error:trace     at onFulfilled (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:65:19)
  oidc-provider:server_error:trace     at D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:54:5
  oidc-provider:server_error:trace     at Promise (<anonymous>)
  oidc-provider:server_error:trace     at Object.co (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:50:10)
  oidc-provider:server_error:trace     at Object.toPromise (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:118:63)
  oidc-provider:server_error:trace     at next (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:99:29)
  oidc-provider:server_error:trace     at onFulfilled (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:69:7)
  oidc-provider:server_error:trace     at D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:54:5
  oidc-provider:server_error:trace     at Promise (<anonymous>)
  oidc-provider:server_error:trace     at Object.co (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:50:10)
  oidc-provider:server_error:trace     at Object.toPromise (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:118:63)
  oidc-provider:server_error:trace     at next (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:99:29)
  oidc-provider:server_error:trace     at onFulfilled (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:69:7)
  oidc-provider:server_error:trace     at D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:54:5
  oidc-provider:server_error:trace     at Promise (<anonymous>)
  oidc-provider:server_error:trace     at Object.co (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:50:10)
  oidc-provider:server_error:trace     at Object.toPromise (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:118:63)
  oidc-provider:server_error:trace     at next (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:99:29)
  oidc-provider:server_error:trace     at onFulfilled (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:69:7)
  oidc-provider:server_error:trace     at D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:54:5
  oidc-provider:server_error:trace     at Promise (<anonymous>)
  oidc-provider:server_error:trace     at Object.co (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:50:10)
  oidc-provider:server_error:trace     at Object.toPromise (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:118:63)
  oidc-provider:server_error:trace     at next (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:99:29)
  oidc-provider:server_error:trace     at onFulfilled (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:69:7)
  oidc-provider:server_error:trace     at D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:54:5
  oidc-provider:server_error:trace     at Promise (<anonymous>)
  oidc-provider:server_error:trace     at Object.co (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:50:10)
  oidc-provider:server_error:trace     at Object.createPromise (D:\pscheler\Documents\Projekte\openID-Connect\node_modules\co\index.js:30:15)
```

I'm using [spirit](https://github.com/spirit-js/spirit) with the express middleware coverter:

```javascript
const app = define([
    routes,
    wrap(any('*'), [express(provider.callback)])
])
```

**Comment by panva** [comment]
I am not familiar with spirit, but the way they describe the project and looking at the "adapter" they do not pass the pure http request downstream, which would have this method defined.

https://nodejs.org/api/http.html#http_response_removeheader_name

**Comment by panva** [comment]
Sorry, cannot work around the differences for every aspiring web framework - my focus is to have it work with the big ones - koa, express

**Comment by Lichtjaeger** [comment]
OK, I switch to express for this microservice.

**Comment by panva** [comment]
Authorization Server a microservice? :) Interesting
