### ISSUE TITLE
step-by-step: heroku: runtime-dyno-metadata: couldn't find feature?

### ISSUE THREAD

**Issue by tony-kerz** [panva/node-oidc-provider#139]
```
❰tony❙~/git/my-provider(git:master)❱✔≻ heroku labs:enable runtime-dyno-metadata                          [127d19h30m]
 ▸    Couldn't find that feature.
```

is this feature optional, or will this inhibit functionality?

__EDIT__:

both of the following commands:

```
heroku open '/.well-known/openid-configuration' # to see your openid-configuration  
heroku open '/auth?client_id=foo&response_type=code&scope=openid' # to start your first Authentication Request
```
yield:

<img width="497" alt="screen shot 2017-08-02 at 8 42 20 am" src="https://user-images.githubusercontent.com/1223231/28874162-9c55d7a4-775e-11e7-87e6-9e70a8afbb0f.png">

and here are the logs:

```
2017-08-02T12:38:34.901422+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/.well-known/openid-configuration" host=frozen-harbor-51097.herokuapp.com request_id=9097f391-aeae-4edb-b2a1-bcab596878e6 fwd="70.181.56.137" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T12:38:35.014844+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=frozen-harbor-51097.herokuapp.com request_id=50eea8ae-722d-445f-8fa2-52a37bfaa1e5 fwd="70.181.56.137" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T12:38:11+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.18 sample#load-avg-5m=0.17 sample#load-avg-15m=0.175 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=11534884kB sample#memory-cached=1114984kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
2017-08-02T12:40:03.021184+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/auth?client_id=foo&response_type=code&scope=openid" host=frozen-harbor-51097.herokuapp.com request_id=0878509c-4f38-4b66-b706-d06c4838eeb6 fwd="70.181.56.137" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T12:40:03.135118+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=frozen-harbor-51097.herokuapp.com request_id=8d4025f9-edd6-428f-8505-7c88d7164f20 fwd="70.181.56.137" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T12:39:35+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.21 sample#load-avg-5m=0.175 sample#load-avg-15m=0.175 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=11538252kB sample#memory-cached=1114968kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
2017-08-02T12:41:02+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.145 sample#load-avg-5m=0.17 sample#load-avg-15m=0.175 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=11538036kB sample#memory-cached=1114972kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
2017-08-02T12:41:02+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.11 sample#load-avg-5m=0.155 sample#load-avg-15m=0.17 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=11538052kB sample#memory-cached=1114968kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
2017-08-02T12:42:22+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.04 sample#load-avg-5m=0.125 sample#load-avg-15m=0.155 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=11537392kB sample#memory-cached=1115080kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
2017-08-02T12:43:48+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.06 sample#load-avg-5m=0.115 sample#load-avg-15m=0.15 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=11537848kB sample#memory-cached=1115076kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
2017-08-02T12:43:48+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.05 sample#load-avg-5m=0.1 sample#load-avg-15m=0.14 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=11539412kB sample#memory-cached=1115056kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
2017-08-02T12:45:09+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.17 sample#load-avg-5m=0.13 sample#load-avg-15m=0.15 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=11539684kB sample#memory-cached=1115060kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
```

**Comment by panva** [comment]
it was a labs feature, probably not available anymore - will have to check, the app won't spool without the variables that it sets.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider-example/commit/c5bbc4aaeb1eb79027a092a9d4308de484ea4f07 takes care of the missing labs feature

**Comment by tony-kerz** [comment]
thanks for the speedy response filipe!

i tried your new branch, but am still seeing errors:

```
2017-08-02T14:31:22.531615+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=gentle-castle-38319.herokuapp.com request_id=e4a8e578-4fe5-4224-b24d-9849fc36ec20 fwd="12.252.19.134" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T14:31:32+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0 sample#load-avg-5m=0 sample#load-avg-15m=0 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=15158588kB sample#memory-cached=278092kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
2017-08-02T14:31:34.162133+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/.well-known/openid-configuration" host=gentle-castle-38319.herokuapp.com request_id=e7240042-60a8-44b5-9164-c76ae18926df fwd="12.252.19.134" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T14:31:34.232837+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=gentle-castle-38319.herokuapp.com request_id=0ecc1472-22e7-4f07-9776-a4ecfe147070 fwd="12.252.19.134" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T14:31:35.677043+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/.well-known/openid-configuration" host=gentle-castle-38319.herokuapp.com request_id=6bc544a7-aea2-41b5-a100-b1ff72cd18d8 fwd="12.252.19.134" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T14:31:35.747093+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=gentle-castle-38319.herokuapp.com request_id=e4d40c5f-e2a4-47db-b02c-9c4e72bdfaac fwd="12.252.19.134" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T14:31:38.042279+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/.well-known/openid-configuration" host=gentle-castle-38319.herokuapp.com request_id=1c5c6d7d-0690-495c-8f77-d8801dff1122 fwd="12.252.19.134" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T14:31:38.112531+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=gentle-castle-38319.herokuapp.com request_id=c073264b-172b-4db6-81a4-0674caf4fed4 fwd="12.252.19.134" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T14:32:30.045109+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/auth?client_id=foo&response_type=code&scope=openid" host=gentle-castle-38319.herokuapp.com request_id=e25d765b-14ff-4bdd-b38e-90e5b7ba18ea fwd="12.252.19.134" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T14:32:30.162227+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=gentle-castle-38319.herokuapp.com request_id=9768d0b2-8cb6-46c0-b865-8d0cc8b7e8c8 fwd="12.252.19.134" dyno= connect= service= status=503 bytes= protocol=https
2017-08-02T14:31:32+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0 sample#load-avg-5m=0 sample#load-avg-15m=0 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=15159308kB sample#memory-cached=278104kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
```

**Comment by panva** [comment]
Well, did you start from the beginning?

**Comment by tony-kerz** [comment]
hey filip,

yes, i did, but i did it again just in case:

cli:
```
❰tony❙~/git❱✔≻ git clone https://github.com/panva/node-oidc-provider-example.git
Cloning into 'node-oidc-provider-example'...
remote: Counting objects: 52, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 52 (delta 4), reused 5 (delta 2), pack-reused 40
Unpacking objects: 100% (52/52), done.
❰tony❙~/git❱✔≻ cd node-oidc-provider-example/
❰tony❙~/git/node-oidc-provider-example(git:master)❱✔≻ git checkout -b tk/mine                                [11h10m]
Switched to a new branch 'tk/mine'
❰tony❙~/git/node-oidc-provider-example(git:tk/mine)❱✔≻ heroku create --addons securekey,heroku-redis:hobby-dev
Creating app... done, ⬢ sheltered-wildwood-20034
Adding securekey... done
Adding heroku-redis:hobby-dev... done
https://sheltered-wildwood-20034.herokuapp.com/ | https://git.heroku.com/sheltered-wildwood-20034.git
❰tony❙~/git/node-oidc-provider-example(git:tk/mine)❱✔≻ heroku config:set X_HEROKU_REMOTE=(git remote get-url heroku)
Setting X_HEROKU_REMOTE and restarting ⬢ sheltered-wildwood-20034... done, v5
X_HEROKU_REMOTE: https://git.heroku.com/sheltered-wildwood-20034.git
❰tony❙~/git/node-oidc-provider-example(git:tk/mine)❱✔≻ cp 00-oidc-minimal/index.js src                       [11h12m]
❰tony❙~/git/node-oidc-provider-example(git≠tk/mine)❱✔≻ git add .                                            [11h12m]✭
❰tony❙~/git/node-oidc-provider-example(git≠tk/mine)❱✔≻ git commit -a -m 'my initial commit'                [11h12m] ✚
[tk/mine 3a4d8f2] my initial commit
 1 file changed, 35 insertions(+)
 create mode 100644 src/index.js
❰tony❙~/git/node-oidc-provider-example(git:tk/mine)❱✔≻ git push heroku master                                    [0m]
Counting objects: 52, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (49/49), done.
Writing objects: 100% (52/52), 34.96 KiB | 0 bytes/s, done.
Total 52 (delta 21), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  >=8.0.0
remote:        engines.npm (package.json):   unspecified (use default)
remote:        engines.yarn (package.json):  unspecified (use default)
remote:
remote:        Resolving node version >=8.0.0...
remote:        Downloading and installing node 8.2.1...
remote:        Using default npm version: 5.3.0
remote:        Resolving yarn version (latest)...
remote:        Downloading and installing yarn (0.28.1)...
remote:        Installed yarn 0.28.1
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (not-found)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v0.28.1
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        [3/4] Linking dependencies...
remote:        warning "ajv-keywords@1.5.1" has incorrect peer dependency "ajv@>=4.10.0".
remote:        [4/4] Building fresh packages...
remote:        Done in 5.81s.
remote:
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 2 cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (nothing to cache)
remote:
remote: -----> Build succeeded!
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:        Done: 19.4M
remote: -----> Launching...
remote:        Released v6
remote:        https://sheltered-wildwood-20034.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/sheltered-wildwood-20034.git
 * [new branch]      master -> master
❰tony❙~/git/node-oidc-provider-example(git:tk/mine)❱✔≻ heroku open '/.well-known/openid-configuration'           [0m]
❰tony❙~/git/node-oidc-provider-example(git:tk/mine)❱✔≻
heroku open '/auth?client_id=foo&response_type=code&scope=openid'
```
logs:
```
2017-08-03T00:59:23.430325+00:00 app[web.1]:     at Function.Module._load (module.js:437:25)
2017-08-03T00:59:23.430326+00:00 app[web.1]:     at Function.Module.runMain (module.js:605:10)
2017-08-03T00:59:23.430326+00:00 app[web.1]:     at startup (bootstrap_node.js:158:16)
2017-08-03T00:59:23.430327+00:00 app[web.1]:     at bootstrap_node.js:575:3
2017-08-03T00:59:23.482567+00:00 heroku[web.1]: Process exited with status 1
2017-08-03T00:59:23.496828+00:00 heroku[web.1]: State changed from starting to crashed
2017-08-03T00:59:29.421104+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/.well-known/openid-configuration" host=sheltered-wildwood-20034.herokuapp.com request_id=4971c574-c278-4ca0-88b6-00709c757d7b fwd="70.181.56.137" dyno= connect= service= status=503 bytes= protocol=https
2017-08-03T00:59:29.543055+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=sheltered-wildwood-20034.herokuapp.com request_id=61a3219c-2a4b-4bc5-bc6c-2e4ad8640fc8 fwd="70.181.56.137" dyno= connect= service= status=503 bytes= protocol=https
2017-08-03T01:00:04.681306+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/auth?client_id=foo&response_type=code&scope=openid" host=sheltered-wildwood-20034.herokuapp.com request_id=3422d461-331b-4633-87bc-9610df21cf9e fwd="70.181.56.137" dyno= connect= service= status=503 bytes= protocol=https
2017-08-03T01:00:04.791121+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=sheltered-wildwood-20034.herokuapp.com request_id=dcc54aeb-103c-4ecd-8120-8dc82588aa5d fwd="70.181.56.137" dyno= connect= service= status=503 bytes= protocol=https
2017-08-03T00:59:42+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.02 sample#load-avg-5m=0.025 sample#load-avg-15m=0.03 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=14253448kB sample#memory-cached=556088kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
2017-08-03T01:00:40+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.005 sample#load-avg-5m=0.02 sample#load-avg-15m=0.025 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=14253424kB sample#memory-cached=556088kB sample#memory-redis=278024bytes sample#hit-rate=1 sample#evicted-keys=0
```

**Comment by panva** [comment]
can you provide the complete heroku log?

**Comment by tony-kerz** [comment]
sure, i was wondering about that, cause in the web ui, the log seemed to start in the middle of a stack trace. then i found out about:
```
heroku logs -n {number of lines}
```
and grabbed this:
```
2017-08-03T06:57:14.988571+00:00 heroku[web.1]: Starting process with command `node src/index.js`
2017-08-03T06:57:16.943191+00:00 app[web.1]: module.js:487
2017-08-03T06:57:16.943212+00:00 app[web.1]:     throw err;
2017-08-03T06:57:16.943213+00:00 app[web.1]:     ^
2017-08-03T06:57:16.943214+00:00 app[web.1]:
2017-08-03T06:57:16.943219+00:00 app[web.1]: Error: Cannot find module '/app/src/index.js'
2017-08-03T06:57:16.943220+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:485:15)
2017-08-03T06:57:16.943220+00:00 app[web.1]:     at Function.Module._load (module.js:437:25)
2017-08-03T06:57:16.943221+00:00 app[web.1]:     at Function.Module.runMain (module.js:605:10)
2017-08-03T06:57:16.943221+00:00 app[web.1]:     at startup (bootstrap_node.js:158:16)
2017-08-03T06:57:16.943222+00:00 app[web.1]:     at bootstrap_node.js:575:3
2017-08-03T06:57:17.051959+00:00 heroku[web.1]: State changed from starting to crashed
2017-08-03T06:57:17.037912+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by panva** [comment]
Well, this should tell you what's wrong ;) not sure what you're pushing to git but maybe you don't have all the changes commited before you push

**Comment by tony-kerz** [comment]
two things i did diff from the steps were:
- name my cloned folder something diff than `my-provider`
- made changes in a branch off `master` called `tk/mine` v directly in `master`

those diffs seemed harmless, maybe it was one of those that caused a problem (or it was something subtle i don't know about), but i tried again following __exactly__ and it worked up till step 3 where i punched in:
```
heroku open '/auth?client_id=foo&response_type=id_token+token&scope=openid+email&nonce=foobar&prompt=login'
```
the browser came up with:
```
Internal Server Error
```
and i see the following in the logs:
```
2017-08-07T23:35:19.529142+00:00 heroku[router]: at=info method=GET path="/auth?client_id=foo&response_type=id_token+token&scope=openid+email&nonce=foobar&prompt=login" host=agile-badlands-90855.herokuapp.com request_id=1bcc71c7-4766-47af-a2ad-bac0e6f01c70 fwd="70.181.56.137" dyno=web.1 connect=1ms service=13ms status=302 bytes=1251 protocol=https
2017-08-07T23:35:19.571857+00:00 heroku[router]: at=info method=GET path="/interaction/44af2f52-cab4-4951-a578-0f506ceb375d" host=agile-badlands-90855.herokuapp.com request_id=30d3d2ac-3bdb-4c9c-b52f-009182205c08 fwd="70.181.56.137" dyno=web.1 connect=1ms service=4ms status=500 bytes=404 protocol=https
2017-08-07T23:35:19.568803+00:00 app[web.1]: see what else is available to you for interaction views Promise { <pending> }
2017-08-07T23:35:19.570897+00:00 app[web.1]: TypeError: Cannot read property 'reason' of undefined
2017-08-07T23:35:19.570900+00:00 app[web.1]:     at view (/app/src/index.js:101:34)
2017-08-07T23:35:19.570901+00:00 app[web.1]:     at expressApp.get (/app/src/index.js:108:7)
2017-08-07T23:35:19.570906+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-08-07T23:35:19.570907+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2017-08-07T23:35:19.570908+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-08-07T23:35:19.570907+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2017-08-07T23:35:19.570909+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:281:22
2017-08-07T23:35:19.570909+00:00 app[web.1]:     at param (/app/node_modules/express/lib/router/index.js:354:14)
2017-08-07T23:35:19.570910+00:00 app[web.1]:     at param (/app/node_modules/express/lib/router/index.js:365:14)
2017-08-07T23:35:19.570911+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2017-08-07T23:35:19.570914+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:284:7
2017-08-07T23:35:19.570911+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
2017-08-07T23:35:19.570912+00:00 app[web.1]:     at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
2017-08-07T23:35:19.570913+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-08-07T23:35:19.570913+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2017-08-07T23:35:19.570915+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2017-08-07T23:34:39+00:00 app[heroku-redis]: source=REDIS sample#active-connections=2 sample#load-avg-1m=0.125 sample#load-avg-5m=0.125 sample#load-avg-15m=0.11 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664268kB sample#memory-free=11384828kB sample#memory-cached=1388540kB sample#memory-redis=301664bytes sample#hit-rate=0.85714 sample#evicted-keys=0
```

**Comment by panva** [comment]
argh, sloppy 2.0 ugprade. will fix
