### ISSUE TITLE
Server Error when parsing client_id running behind proxy

### ISSUE THREAD

**Issue by Lanthius** [panva/node-oidc-provider#152]
Hi,

I have a node-oidc-provider (with express) running behind a proxy (API Connect). For testing purposes the devInteractions feature is set to true. My Auth call to the proxy gets forwarded to the node-oidc-provider, which tries to redirect to the default login screen (at the point of redirecting (302), it sees all the query parameters (client_id etc). When the /interaction/6a67.. url is called, i get a 500 response and the following debug error:

ERR 2017-09-14T10:01:27.994Z oidc-provider:server_error uuid=5df26b3e-3420-4823-b0b9-6bb754f10fa6 path=/interaction/6a67dc65-b1e4-4f28-8363-a9f004211083 error=TypeError: Cannot read property 'client_id' of undefined at interactionRender (/home/vcap/app/node_modules/oidc-provider/lib/actions/interaction.js:23:65) at <anonymous> at process._tickCallback (internal/process/next_tick.js:169:7)

I'm assuming that the uuid should remain static through the whole process and the fact that the uuid and the path /interaction/{uuid} are different is why it doesn't have any reference to the originally transferred parameters? Any ideas? 

(Note: When i don't run it behind a proxy, everything works as intended. Also I have app.proxy set to true.)

Thanks for your time.

**Comment by panva** [comment]
what's the `oidc-provider` version?

**Comment by Lanthius** [comment]
2.3.0

Thanks.

**Comment by panva** [comment]
I'm actually without a clue. This just doesn't seem plausable with `devInteractions`... on. Can you post a full trace with `DEBUG=oidc-provider:*`?

Do you have oidc-provider app mounted to another app, i.e. your own koa or express app? If so, can you paste the setup too?

**Comment by Lanthius** [comment]
DEBUG=oidc-provider:* output below:

2017-09-14T14:16:53.80+0200 [APP/PROC/WEB/0] ERR 2017-09-14T12:16:53.805Z oidc-provider:authentication:accepted uuid=d632b9de-a2b0-4b4f-a72a-d5e4be93ee4e Params { acr_values: undefined, claims: undefined, claims_locales: undefined, client_id: 'client01', code_challenge: undefined, code_challenge_method: undefined, display: undefined, id_token_hint: undefined, login_hint: undefined, max_age: undefined, nonce: '123', prompt: undefined, redirect_uri: 'https://www.getpostman.com/oauth2/callback', registration: undefined, request: undefined, request_uri: undefined, response_mode: 'fragment', response_type: 'id_token', scope: 'openid', state: '321', ui_locales: undefined }

2017-09-14T14:16:53.87+0200 [APP/PROC/WEB/0] ERR 2017-09-14T12:16:53.864Z oidc-provider:authentication:interrupted uuid=d632b9de-a2b0-4b4f-a72a-d5e4be93ee4e interaction={ error: 'login_required', error_description: 'End-User authentication is required', reason: 'no_session', reason_description: 'Please Sign-in to continue.' }

2017-09-14T14:16:53.94+0200 [APP/PROC/WEB/0] ERR 2017-09-14T12:16:53.946Z oidc-provider:server_error uuid=9cd64c41-3036-4987-b158-2e7cb16b313a path=/interaction/d632b9de-a2b0-4b4f-a72a-d5e4be93ee4e error=TypeError: Cannot read property 'client_id' of undefined at interactionRender (/home/vcap/app/node_modules/oidc-provider/lib/actions/interaction.js:23:65) at <anonymous> at process._tickCallback (internal/process/next_tick.js:169:7)

2017-09-14T14:16:53.96+0200 [APP/PROC/WEB/0] ERR 2017-09-14T12:16:53.958Z oidc-provider:server_error:trace TypeError: Cannot read property 'client_id' of undefined
2017-09-14T14:16:53.96+0200 [APP/PROC/WEB/0] ERR     at interactionRender (/home/vcap/app/node_modules/oidc-provider/lib/actions/interaction.js:23:65)
2017-09-14T14:16:53.96+0200 [APP/PROC/WEB/0] ERR     at <anonymous>
2017-09-14T14:16:53.96+0200 [APP/PROC/WEB/0] ERR     at process._tickCallback (internal/process/next_tick.js:169:7)


Here is the basic set-up (its a standalone provider, the app does nothing else):

const express = require('express');
const Provider = require('oidc-provider');
var cfenv = require('cfenv');

var app = express();

const oidc = new Provider(appEnv.url, {
    features: {devInteractions: true},
    claims: {
        email: ['email', 'email_verified'],
        phone: ['phone_number', 'phone_number_verified']
    }});
oidc.initialize({
    clients: [
        {
            client_id: 'client01',
            grant_types: ['implicit'],
            response_types: ['id_token'],
            redirect_uris: ['https://www.getpostman.com/oauth2/callback'],
            token_endpoint_auth_method: 'none'
        }
    ]
}).then(function () {
    app.use('/', oidc.callback);
    oidc.app.proxy = true;
    app.enable('trust proxy');
    app.listen(appEnv.port);
    console.log("Running on: " + appEnv.url);
});

**Comment by panva** [comment]
I just ran this behind a proxy as well as without it just fine with no changes to the code.

```
  "dependencies": {
    "express": "^4.15.4",
    "oidc-provider": "^2.3.0"
  }
```

**Comment by Lanthius** [comment]
ok, thanks for taking a look into it for me. The problem seems to lie squarely with the API Connect gateway then. Sadly its not that easy to find logs of what is happening within the gateway itself. I'll just find another proxy solution :)

Thanks again for your time.
