### ISSUE TITLE
Session redis adapter stringify's to '[object Object]': ''

### ISSUE THREAD

**Issue by KleptoKat** [panva/node-oidc-provider#218]
I'm working with a default redis adapter and when session calls 'save' it copies the Session object and sends it to the adapter to upsert into Redis. Problem is, when the upsert function calls JSON.stringify it stringifies to `'[object Object]': ''`. And so when `provider.interactionDetails` is called, it receives these details: `{ '[object Object]': '',
  id: '04cc26c3-1502-4bcc-bb2d-394aec4ef670' }`

The redis tester works, so what am I doing wrong? I'm using Typescript 2.7.1 and oidc-provider 2.13.1. I have sessionManagement enabled.

Here is my upsert code in redis_adapter.ts:

	public upsert(id, payload, expiresIn) {
		const key = this.key(id);
		let toStore = payload;

		// Clients are not simple objects where value is always a string
		// redis does only allow string values =>
		// work around it to keep the adapter interface simple
		if (this.name === 'Client' || this.name === 'Session') {
			toStore = { dump: JSON.stringify(payload) };
		}

		const multi = client.multi();
		multi.hmset(key, toStore, undefined);

		if (expiresIn) {
			multi.expire(key, expiresIn);
		}

		if (toStore.grantId) {
			const grantKey = grantKeyFor(toStore.grantId);
			multi.rpush(grantKey, key);
		}

		return multi.exec();
	}

On call to auth:

` 2018-02-26T00:24:46.123Z - info: [auth] GET /auth?client_id=foo&response_type=id_token+token&scope=openid+email&nonce=foobar&prompt=login 302 22.882 ms - 129 `

Then redirect to /interaction/:grant

` 2018-02-26T00:24:46.132Z - info: [auth] see what else is available to you for interaction views 
{ '[object Object]': '',
  id: '04cc26c3-1502-4bcc-bb2d-394aec4ef670' }
2018-02-26T00:24:46.133Z - info: [auth] GET /interaction/04cc26c3-1502-4bcc-bb2d-394aec4ef670 500 1.504 ms - 380
TypeError: Cannot read property 'reason' of undefined
    at /usr/src/nub.auth/dist/nub.auth/src/interaction.js:48:49
    at /usr/src/nub.auth/dist/nub.auth/src/interaction.js:55:19
    at <anonymous> `

**Comment by KleptoKat** [comment]
Not sure how to mark this solved, but I did it!

I must be running on a different version of ioredis, because hmset was uploading [object Object] to the key directly. Problem was that upsert was stringifying the payload, creating the toStore object with that string as the dump parameter, and then passing the object directly to hmset which only accepts anything but it converts it to a string. So it will call Object.tostring on the toStore object { dump: payload } which just returns '[object Object]'.

I might detail the tests a little more to check for this, and fix the example adapter. I need sleep.
