### ISSUE TITLE
iframe session_state not same as authenticate session_state

### ISSUE THREAD

**Issue by robaca** [panva/node-oidc-provider#248]
I just try to implement OpenID Connect Session Management in our app against node-oidc-provider. I'm taking the `session_state` query parameter from the authentication request and pass that via ```postMessage(`${clientId} ${sessionState}`, ...)``` to the session-check iframe, but the values always immediately differ and I get back "changed".  There are no errors in the logs, even with debugging enabled.

Any idea what I could do wrong?

**Comment by robaca** [comment]
One more info: 
```
var opbs = getOPBrowserState(clientId);
```
returns undefined

**Comment by panva** [comment]
Hi @robaca,

there's likely something wrong with your cookie/domain/protocol setup. 

Please open chrome console on the RP page where the OP frame is loaded, switch the context from `top` to your respective `rp frame` identifier and access `document.cookie`. It will likely not include the session state cookies.

**Comment by panva** [comment]
@robaca You can also see it working [here](https://tranquil-reef-95185.herokuapp.com), login in one tab, open another one and log out in it, the first one should alert with the status "changed" after doing so.

**Comment by robaca** [comment]
@panva Maybe you are right, but I didn't find the root cause yet. 

My config looks like this:
```
        this.server = express()
        this.server.use(bodyParser.json())

       const oidc = new Provider(`http://127.0.0.1:${this.port}/oidc`, {
            claims: {
                openid: [ ... ]
            },
            features: {
                claimsParameter: true,
                discovery: true,
                encryption: true,
                // introspection: true,
                // registration: true,
                request: true,
                revocation: true,
                sessionManagement: true
            },
            findById: async (_: any, id: string) => {
                const accountId = this.accountIdForUser(id)
                return accountId ? {
                    accountId,
                    claims: async () => Promise.resolve(this.claimsForUser(accountId))
                } : undefined
            }
        })

        await oidc.initialize({
            clients: [
                {
                    client_id: 'my-client-id',
                    client_secret: 'secret',
                    redirect_uris: [ 'http://127.0.0.1:3011/public/authenticate' ],
                    token_endpoint_auth_method: 'client_secret_post'
                }
            ]
        })
        this.server.use(rewrite('/.well-known/openid-configuration*', '/oidc/.well-known/openid-configuration$1'))
        this.server.use('/oidc', oidc.callback)
```
One other thing I encountered: 
Closing the OP session does not happen. After clicking yes on "Do you want to logout from OP too?" I still get transparently re-logged-in

My client is working as expected in combination with another OIDC provider.

**Comment by panva** [comment]
I'm seeing no issues on my end with your setup [running](https://gist.github.com/panva/a613a35f063926f14be92fe9cba1aecf).

start OP server with `node index`, authorize by navigating to `http://127.0.0.1:3000/oidc/auth?client_id=client&response_type=code&scope=openid`, finish authorization, from the callback get full `session_state`, e.g. `5e92d0730d975af997903c8f65ecfec4c8ea9aca595d3d924d825dd35dbd30b1.7393791cccccb98b` and using `npm -ig http-server` run the two html files, navigate to `http://127.0.0.1:8080/`, first message i get from the RP frame is "unchanged", cookies are present.

**Comment by robaca** [comment]
I'm getting closer to a solution.

My current process consists of two express instances - one for the main application and one for the oidc-provider. It seems that both of them register cookies with the same domain but without port number sometimes, and so requests to both instances seem to "steal" cookies for the other port.

I already tried to add cookie options like this:
```
             cookies: {
                long: {
                    signed: false,
                    domain: `http://127.0.0.1:${this.port}`
                },
                short: {
                    signed: false,
                    domain: `http://127.0.0.1:${this.port}`
                }
            }
```
But now I get the following message:
```
  oidc-provider:server_error uuid=502873f0-dbb4-4cc3-9582-5740d13eb0b4 
  path=/interaction/502873f0-dbb4-4cc3-9582-5740d13eb0b4 
  method=GET 
  error={ AssertionError [ERR_ASSERTION]: id must be provided to Session#find 
  at Function.find (/service/node_modules/oidc-provider/lib/models/session.js:82:7) 
  at Provider.getInteraction (/service/node_modules/oidc-provider/lib/provider.js:62:42) 
  at Provider.interactionDetails (/service/node_modules/oidc-provider/lib/provider.js:182:46) 
  at interactionRender (/service/node_modules/oidc-provider/lib/actions/interaction.js:23:40) 
  at dispatch (/service/node_modules/oidc-provider/node_modules/koa-compose/index.js:42:32) 
  at /service/node_modules/oidc-provider/node_modules/koa-compose/index.js:34:12 
  at dispatch (/service/node_modules/koa-compose/index.js:44:32) 
  at next (/service/node_modules/koa-compose/index.js:45:18) 
  at apiErrorHandler (/service/node_modules/oidc-provider/lib/shared/error_handler.js:11:13) 
  at dispatch (/service/node_modules/koa-compose/index.js:44:32) 
  generatedMessage: false, 
  name: 'AssertionError [ERR_ASSERTION]', code: 'ERR_ASSERTION', actual: undefined, expected: true, operator: '==' }
```

**Comment by panva** [comment]
Cookies do not provide isolation by port. Instead of changing the domain use `cookies.names` configuration option to change the cookie names.

**Comment by robaca** [comment]
Hi @panva many thanks, renaming the cookies did the job.
