### ISSUE TITLE
Error getting interaction details

### ISSUE THREAD

**Issue by alejandrogj** [panva/node-oidc-provider#300]
Hello!

First of all, thanks for your work developing this package.

I'm using the example in the repo (https://github.com/panva/node-oidc-provider/tree/master/example) as a starting point.

When sending an auth request

`http://localhost:3000/auth?response_type=code&scope=openid&client_id=client1&redirect_uri=https://example.com`

i get this server error

```
  TypeError: Cannot read property 'client_id' of undefined
      at router.get (/home/agonzalez/git/node-oidc/example-node-oidc/src/index.js:61:62)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```
in this part of the code

```
  router.get('/interaction/:grant', async (ctx, next) => {
    const details = await provider.interactionDetails(ctx.req);
    const client = await provider.Client.find(details.params.client_id);
```
Printing what's inside "details" i get

`Session { id: '14a4dc43-43c9-478d-b4d7-690386f973ed' }`

It seems that i'm not getting the right interaction details.

This is the log output

```
  oidc-provider:authentication:accepted uuid=14a4dc43-43c9-478d-b4d7-690386f973ed Params { acr_values: undefined, claims: undefined, claims_locales: undefined, client_id: 'client1', code_challenge: undefined, code_challenge_method: undefined, display: undefined, id_token_hint: undefined, login_hint: undefined, max_age: undefined, nonce: undefined, prompt: undefined, redirect_uri: 'https://example.com', registration: undefined, request: undefined, request_uri: undefined, response_mode: 'query', response_type: 'code', scope: 'openid', state: undefined, ui_locales: undefined } +0ms
  oidc-provider:authentication:interrupted uuid=14a4dc43-43c9-478d-b4d7-690386f973ed interaction={ error: 'login_required', error_description: 'End-User authentication is required', reason: 'no_session', reason_description: 'Please Sign-in to continue.' } +0ms
Session { id: '14a4dc43-43c9-478d-b4d7-690386f973ed' }

  TypeError: Cannot read property 'client_id' of undefined
      at router.get (/home/agonzalez/git/node-oidc/example-node-oidc/src/index.js:61:62)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```
And this is my adapter (i'm using mongodb)

```
const { MongoClient } = require('mongodb'); // eslint-disable-line import/no-unresolved
const { snakeCase } = require('lodash');
const { mongoConfig } = require('../settings');

let DB;

class CollectionSet extends Set {
  add(name) {
    const nu = this.has(name);
    super.add(name);
    if (!nu) {
      DB.collection(name).createIndexes([
        { key: { grantId: 1 } },
        { key: { expiresAt: 1 }, expireAfterSeconds: 0 },
      ]).catch(console.error); // eslint-disable-line no-console
    }
  }
}

const collections = new CollectionSet();

class MongoAdapter {
  constructor(name) {
    this.name = snakeCase(name);
    collections.add(this.name);
  }

  coll(name) {
    return this.constructor.coll(name || this.name);
  }

  static coll(name) {
    return DB.collection(name);
  }

  destroy(id) {
    return this.coll().findOneAndDelete({ _id: id })
      .then((found) => {
        if (found.value && found.value.grantId) {
          const promises = [];

          collections.forEach((name) => {
            promises.push(this.coll(name).deleteMany({ grantId: found.value.grantId }));
          });

          return Promise.all(promises);
        }
        return undefined;
      });
  }

  consume(id) {
    return this.coll().findOneAndUpdate({ _id: id }, { $currentDate: { consumed: true } });
  }

  find(id) {
    return this.coll().find({ client_id: id }).limit(1).next();
  }

  upsert(_id, payload, expiresIn) {
    let expiresAt;

    if (expiresIn) {
      expiresAt = new Date(Date.now() + (expiresIn * 1000));
    }

    // HEROKU EXAMPLE ONLY, do not use the following block unless you want to drop dynamic
    //   registrations 24 hours after registration
    if (this.name === 'client') {
      expiresAt = new Date(Date.now() + (24 * 60 * 60 * 1000));
    }

    const document = Object.assign(payload, expiresAt && { expiresAt });

    // the above does not work for _id sharded collections, use the one below
    // const document = Object.assign(payload, { _id }, expiresAt && { expiresAt });

    return this.coll().updateOne({ _id }, { $set: document }, { upsert: true });
  }

  static async connect() {
    const connection = await MongoClient.connect(
      `mongodb://${mongoConfig.host}:${mongoConfig.port}/${mongoConfig.db}`,
      { auth: { user: mongoConfig.user, password: mongoConfig.password } },
    );

    DB = connection.db(connection.s.options.dbName);
  }
}

module.exports = MongoAdapter;

```

Thanks!

**Comment by panva** [comment]
Running `MONGODB_URI=mongodb://localhost/test ISSUER=http://localhost:8000 PORT=8000 node example` works just fine for me.

How do you `run`/what command the example?

**Comment by alejandrogj** [comment]
Apparently something was wrong with my client registered in the mongodb, i added this client manually in the "client" collection

I tried again using the "registration" endpoint and the authorization request redirects me to the "Sign-in" page.

Thanks for your quick response!
