### ISSUE TITLE
server_error (oops something went wrong)

### ISSUE THREAD

**Issue by s-a** [panva/node-oidc-provider#318]
I regularly get the following error message while login process.
The thing is that there does not apear an error on the oauth server. The client log looks like:

```
11|app     |       at dispatch (/web/app-server/node_modules/koa-router/lib/router.js:351:31)
11|app     |       at dispatch (/web/app-server/node_modules/koa-compose/index.js:42:32)
11|app     |       at app.use (/web/app-server/lib/app.js:83:10)
11|app     | [2018-07-17T13:52:12.962Z] DEBUG: app-server_v1.0.2/29104 on csx-staging (/web/app-server/lib/app.js:85 in app.use): server_error (oops something went wrong)
11|app     |   OpenIdConnectError: server_error (oops something went wrong)
11|app     |       at Client.authorizationCallback (/web/app-server/node_modules/openid-client/lib/client.js:328:29)
11|app     |       at router.get (/web/app-server/lib/app.js:296:17)
11|app     |       at dispatch (/web/app-server/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
11|app     |       at next (/web/app-server/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
11|app     |       at /web/app-server/node_modules/koa-router/lib/router.js:346:16
11|app     |       at dispatch (/web/app-server/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
11|app     |       at /web/app-server/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
11|app     |       at dispatch (/web/app-server/node_modules/koa-router/lib/router.js:351:31)
11|app     |       at dispatch (/web/app-server/node_modules/koa-compose/index.js:42:32)
11|app     |       at app.use (/web/app-server/lib/app.js:83:10)
```

Where line 83 in app.js is 

```javascript
await next()
```

in the following code 

```javascript
	app.use(async (ctx, next) => {
		try {
			await next()
		} catch (error) {
			logger.debug(error)

			// TODO:
			// respond and consume error
			// ctx.redirect(ctx.href)
		}
	})
```
From this point no login is possible anymore also no logout I guess every oauth process method is broken at this point.

I figuered out that it resolves the error to delete the mongo db database for oauth sessions. Any Idea what we are missing or what could go wrong?

**Comment by s-a** [comment]
Thanks for the hint. I missed the the `DEBUG` config section. This provides detailed error log. I see now I made mistakes in code.

**Comment by hadelnasr** [comment]
how to set DEBUG=oidc-provider:*? using ubuntu
