### ISSUE TITLE
example/adapters/sequelize.js not working on MySQL

### ISSUE THREAD

**Issue by kaito3desuyo** [panva/node-oidc-provider#322]
Hello.
Excuse me again.

I tried using sequelize adapter with sqlite. This was successful.
However, changing the setting to mysql will generate an error.
```
const sequelize = new Sequelize('myDatabase', 'myUserName', 'MyPassword', {
  dialect: 'mysql'
});
```
it was unhandledRejection, we observed with ```process.on('unhandledRejection', console.dir);```
The errors are as follows.

```
Executing (default): CREATE TABLE IF NOT EXISTS `Sessions` (`id` VARCHAR(255) , `grantId` UUIDV4, `userCode` UUIDV4, `data` JSON, `expiresAt` DATETIME, `consumedAt` DATETIME, `createdAt` DATETIME NOTNULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
{ SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UUIDV4, `userCode` UUIDV4, `data` JSON, `expiresAt` DATETIME, `consumedAt` DATET' at line 1
    at Query.formatError (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
From previous event:
    at Query.run (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/sequelize.js:555:8)
    at /home/seapolis/Dropbox/Program/trarepo-server/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.createTable (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/query-interface.js:279:29)
    at Promise.try.then.then (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/model.js:1128:39)
From previous event:
    at Function.sync (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/model.js:1128:8)
    at Promise.each.model (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/sequelize.js:719:50)
From previous event:
    at Promise.try.then.then (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/sequelize.js:719:22)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Sequelize.sync (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/sequelize/lib/sequelize.js:706:8)
    at Function.connect (/home/seapolis/Dropbox/Program/trarepo-server/oidc/adapter.js:97:22)
    at Provider.initializeAdapter (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/oidc-provider/lib/helpers/initialize_adapter.js:11:38)
    at initializeKeystore.call.then (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/oidc-provider/lib/provider.js:146:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  name: 'SequelizeDatabaseError',
  parent:
   { Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDBserver version for the right syntax to use near 'UUIDV4, `userCode` UUIDV4, `data` JSON, `expiresAt` DATETIME, `consumedAt` DATET' at line 1
    at Packet.asError (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/packets/packet.js:716:13)
    at Query.Command.execute (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
     code: 'ER_PARSE_ERROR',
     errno: 1064,
     sqlState: '42000',
     sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'UUIDV4, `userCode` UUIDV4, `data` JSON, `expiresAt` DATETIME, `consumedAt` DATET\' at line 1',
     sql: 'CREATE TABLE IF NOT EXISTS `Sessions` (`id` VARCHAR(255) , `grantId` UUIDV4, `userCode` UUIDV4, `data` JSON, `expiresAt` DATETIME, `consumedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;' },
  original:
   { Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDBserver version for the right syntax to use near 'UUIDV4, `userCode` UUIDV4, `data` JSON, `expiresAt` DATETIME, `consumedAt` DATET' at line 1
    at Packet.asError (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/packets/packet.js:716:13)
    at Query.Command.execute (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/seapolis/Dropbox/Program/trarepo-server/node_modules/mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
     code: 'ER_PARSE_ERROR',
     errno: 1064,
     sqlState: '42000',
     sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'UUIDV4, `userCode` UUIDV4, `data` JSON, `expiresAt` DATETIME, `consumedAt` DATET\' at line 1',
     sql: 'CREATE TABLE IF NOT EXISTS `Sessions` (`id` VARCHAR(255) , `grantId` UUIDV4, `userCode` UUIDV4, `data` JSON, `expiresAt` DATETIME, `consumedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;' },
  sql: 'CREATE TABLE IF NOT EXISTS `Sessions` (`id` VARCHAR(255) , `grantId` UUIDV4, `userCode` UUIDV4, `data` JSON, `expiresAt` DATETIME, `consumedAt` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;' }
```

Is there any solution?
Thank you

**Comment by panva** [comment]
Sorry, unfortunately something i can not help with. Adapters are userland to me :)
