### ISSUE TITLE
Adapter test fails: expected code to be found

### ISSUE THREAD

**Issue by P4sca1** [panva/node-oidc-provider#338]
I wrote my own mongodb adapter using mongoose but it fails with the message above. I tried to find out why a saved authorization code can't be retreived using the find method and I came across this assertion error:

```
{ AssertionError [ERR_ASSERTION]: jwt jti invalid
    at assertPayload (/Users/pascal/code/oidc-server/node_modules/oidc-provider/lib/helpers/jwt.js:82:14)
    at Function.verify (/Users/pascal/code/oidc-server/node_modules/oidc-provider/lib/models/formats/opaque.js:57:5)
    at Function.find (/Users/pascal/code/oidc-server/node_modules/oidc-provider/lib/models/base_token.js:91:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: 'uIytgijKWdNsjrPOubJpMfS7ln7',
  operator: '==' }
```

This is the stored authorization code that it fails to find (it exists in the database, seems to be a jwt issue?):

```
{
    "_id" : "uIytgijKWdNsjrPOubJpMfS7ln7",
    "__v" : 0,
    "expiresAt" : ISODate("2018-08-01T11:32:50.353Z"),
    "payload" : {
        "iat" : 1533122570,
        "iss" : "http://localhost:5000",
        "exp" : 1533123170,
        "accountId" : "364de0a2-47c0-48ed-ba53-f271a682f726",
        "authTime" : 1533122570,
        "claims" : {
            "id_token" : {
                "email" : null,
                "family_name" : {
                    "essential" : true
                },
                "gender" : {
                    "essential" : false
                },
                "given_name" : {
                    "value" : "John"
                },
                "locale" : {
                    "values" : [ 
                        "en-US", 
                        "en-GB"
                    ]
                },
                "middle_name" : {}
            }
        },
        "clientId" : "5d7328f1-db88-4722-a78e-232fc30db579",
        "grantId" : "975533dc-b1fc-4068-99d1-a830244b4694",
        "nonce" : "0.16027523224814533",
        "redirectUri" : "http://client.example.com/cb",
        "scope" : "openid profile",
        "jti" : "uIytgijKWdNsjrPOubJpMfS7ln7",
        "kind" : "AuthorizationCode"
    }
}
```

Is there something wrong with my key store?

**Comment by panva** [comment]
Would have to see the adapter. But please try to see how the example one is handling this.

**Comment by P4sca1** [comment]
I used the example adapter as a guideline, here's my code:

```
const mongoose = require('mongoose')
const Schema = mongoose.Schema

class MongooseAdapter {
    /**
     * Creates an instance of MongooseAdapter for an oidc-provider model.
     * @param {String} name Name of the oidc-provider model. One of "Session", "AccessToken",
     * "AuthorizationCode", "RefreshToken", "ClientCredentials", "Client", "InitialAccessToken",
     * "RegistrationAccessToken", "DeviceCode".
     */
    constructor(name) {
        const schema = new Schema({
            _id: String,
            payload: Object,
            consumed: Boolean,
            expiresAt: {
                type: Date,
                index: {
                  expireAfterSeconds: 0
                }
            }
        })

        this.model = mongoose.model(name, schema)
    }

    /**
     * Update or Create an instance of an oidc-provider model.
     * @param {String} id Identifier that oidc-provider will use to reference this model instance for
     * future operations.
     * @param {Object} payload Object with all properties intended for storage.
     * @param {Number} expiresIn Number of seconds intended for this model to be stored.
     * @return {Promise} Promise fulfilled when the operation succeeded. Rejected with error when
     * encountered.
     */
    async upsert(id, payload, expiresIn) {
        /**
         * When this is one of AccessToken, AuthorizationCode, RefreshToken, ClientCredentials,
         * InitialAccessToken or RegistrationAccessToken the payload will contain the following
         * properties depending on the used `formats` value for the given token (or default).
         *
         * when `legacy`
         * - grantId {String} grant identifier, tokens with the same value belong together
         * - header {String} oidc-provider tokens are themselves JWTs, this is the header part of the token
         * - payload {String} second part of the token
         * - signature {String} the signature of the token
         *
         * Hint for legacy format: you can JSON.parse(base64decode( ... )) the header and payload to get
         * the token properties and store them too, they may be helpful for getting insights on your usage.
         * Modifying any of header, payload or signature values will result in the token being invalid,
         * remember that oidc-provider will do a JWT signature check of both the received and stored
         * token to detect potential manipulation.
         *
         * when `opaque`
         * - jti {String} unique identifier of the token
         * - kind {String} token class name
         * - exp {Number} - timestamp of the token's expiration
         * - iat {Number} - timestamp of the token's creation
         * - iss {String} - issuer identifier, useful in multi-provider instance apps
         * - accountId {String} - account identifier the token belongs to
         * - clientId {String} client identifier the token belongs to
         * - aud {array of Strings} array of audiences the token is intended for
         * - authTime {Number} timestamp of the end-user's authentication
         * - claims {Object} requested claims (see claims parameter in OIDC Core 1.0)
         * - codeChallenge {String} - client provided PKCE code_challenge value
         * - codeChallengeMethod {String} - client provided PKCE code_challenge_method value
         * - grantId {String} - grant identifier, tokens with the same value belong together
         * - nonce {String} - random nonce from an authorization request
         * - redirectUri {String} - redirect_uri value from an authorization request
         * - scope {String} - scope value from on authorization request
         * - sid {String} - session identifier the token comes from
         * - gty {String} - [AccessToken, RefreshToken only] space delimited grant values, indicating
         *     the grant type(s) they originate from (implicit, authorization_code, refresh_token or
         *     device_code) the original one is always first, second is refresh_token if refreshed
         * - params {Object} - [DeviceCode only] an object with the authorization request parameters
         *     as requested by the client with device_authorization_endpoint
         * - deviceInfo {Object} - [DeviceCode only] an object with details about the
         *     device_authorization_endpoint request
         * - error {String} - [DeviceCode only] - error from authnz to be returned to the polling client
         * - errorDescription {String} - [DeviceCode only] - error_description from authnz to be returned
         *     to the polling client
         *
         * when `jwt`
         * - same as `opaque` with the addition of
         * - jwt {String} - the jwt value returned to the client
         *
         * Hint2: in order to fulfill all OAuth2.0 behaviors in regards to invalidating and expiring
         * potentially misused or sniffed tokens you should keep track of all tokens that belong to the
         * same grantId.
         *
         * Client model will only use this when registered through Dynamic Registration features and
         * will contain all client properties.
         *
         * OIDC Session model payload contains the following properties:
         * - account {String} the session account identifier
         * - authorizations {Object} object with session authorized clients and their session identifiers
         * - loginTs {Number} timestamp of user's authentication
         * - exp {Number} timestamp of the session's expiration
         *
         * Short-lived Interaction Session model payload contains the following properties:
         * - accountId {String} current session account identifier
         * - returnTo {String} after resolving interactions send the user-agent to this url
         * - interaction {Object} details on the interaction details (error, reason code and descriptions)
         * - exp {Number} timestamp of the session's expiration
         * - uuid {String} - uuid of the grant
         * - params {Object} - parsed recognized parameters object
         * - signed {array} - array of parameter names (keys) that were received from a signed and/or
         *                    symmetrically encrypted request/_uri object
         * - result {Object} - interaction results object is expected here
         */
        
        let expiresAt;

        if (expiresIn) {
          expiresAt = new Date(Date.now() + (expiresIn * 1000));
        }

        await this.model.findOneAndUpdate({ _id: id }, {
            _id: id,
            payload,
            ...(expiresAt ? { expiresAt } : undefined)
        }, { upsert: true }).exec()
    }

    /**
     * Return previously stored instance of an oidc-provider model.
     * @param {String} id Identifier of oidc-provider model
     * @return {Promise} Promise fulfilled with either Object (when found and not dropped yet due to
     * expiration) or falsy value when not found anymore. Rejected with error when encountered.
     */
    async find(id) {
        return await this.model.findById(id)
    }

    /**
     * Return previously stored instance of DeviceCode. You only need this method for the deviceCode
     * feature.
     * @param {String} userCode the user_code value associated with a DeviceCode instance
     * @return {Promise} Promise fulfilled with either Object (when found and not dropped yet due to
     * expiration) or falsy value when not found anymore. Rejected with error when encountered.
     */
    async findByUserCode(userCode) {
        // Not using device code atm
    }

    /**
     * Mark a stored oidc-provider model as consumed (not yet expired though!). Future finds for this
     * id should be fulfilled with an object containing additional property named "consumed" with a
     * truthy value (timestamp, date, boolean, etc).
     * @param {String} id Identifier of oidc-provider model
     * @return {Promise} Promise fulfilled when the operation succeeded. Rejected with error when
     * encountered.
     */
    async consume(id) {
        return await this.model.findOneAndUpdate({ _id: id }, { consumed: true }).exec()
    }

    /**
     * Destroy/Drop/Remove a stored oidc-provider model and other grant related models. Future finds
     * for this id should be fulfilled with falsy values.
     * @param {String} id Identifier of oidc-provider model
     * @return {Promise} Promise fulfilled when the operation succeeded. Rejected with error when
     * encountered.
     */
    async destroy(id) {
        const found = await this.model.findByIdAndRemove(id).exec()

        /**
         * Tokens with the same grant id belong together. To query your persistancy store for the grantId of this token
         * and also trigger a chain of removals for all related tokens is recommended.
         */
        if (found.payload && found.payload.grantId) {
            await this.model.deleteMany({ 'payload.grantId': found.payload.grantId }).exec()
        }
    }

    /**
     * A one time hook called when initializing the Provider instance, use to establish necessary
     * connections if applicable, afterwards only new instances will initialized.
     * @param {Provider} provider Provider instance for which the connection is needed
     * @return {Promise} Promise fulfilled when the operation succeeded. Rejected with error when
     * encountered.
     */
    static async connect(provider) {
        await mongoose.connect('mongodb://localhost:27017/oidc', { useNewUrlParser: true })
    }
}

module.exports = MongooseAdapter;
```

**Comment by P4sca1** [comment]
Okay I was able to trace the problem down to the opaque verify function not getting the payload but the whole token object. It gets this
```
{ _id: 'dDid5vAVC_ooT4Oc6b5shosEyh0',
  __v: 0,
  expiresAt: 2018-08-01T11:56:00.946Z,
  payload:
   { iat: 1533123960,
     iss: 'http://localhost:5000',
     exp: 1533124560,
     accountId: '70501757-ce23-40c8-bbb7-442dc6e748a7',
     authTime: 1533123960,
     claims: { id_token: [Object] },
     clientId: '53230078-3b43-45ed-bcc2-a5a9598cc39c',
     grantId: 'd6ab290c-2089-4eea-b17a-5eb2f06daa3b',
     nonce: '0.1365099590414951',
     redirectUri: 'http://client.example.com/cb',
     scope: 'openid profile',
     jti: 'dDid5vAVC_ooT4Oc6b5shosEyh0',
     kind: 'AuthorizationCode' } }
```

instead of this

```
   { iat: 1533123960,
     iss: 'http://localhost:5000',
     exp: 1533124560,
     accountId: '70501757-ce23-40c8-bbb7-442dc6e748a7',
     authTime: 1533123960,
     claims: { id_token: [Object] },
     clientId: '53230078-3b43-45ed-bcc2-a5a9598cc39c',
     grantId: 'd6ab290c-2089-4eea-b17a-5eb2f06daa3b',
     nonce: '0.1365099590414951',
     redirectUri: 'http://client.example.com/cb',
     scope: 'openid profile',
     jti: 'dDid5vAVC_ooT4Oc6b5shosEyh0',
     kind: 'AuthorizationCode' }
```

which is why verification fails.

**Comment by panva** [comment]
Also your other methods refer to payload.

**Comment by panva** [comment]
In other words, you can choose your data model but what comes in to upsert’s second argument is what needs to come out of find. You can “payload” the thing but transform it on the find. And make sure consumed is returned too in the same manner.

**Comment by P4sca1** [comment]
Okay, everything is working now. I switched from mongoose to the default mongodb client, as mongoose is not very useful in this case. Thank you for your help!
