### ISSUE TITLE
oidc-provider cannot update cookies in /session/end

### ISSUE THREAD

**Issue by fauxsoup** [panva/node-oidc-provider#408]
**Describe the bug**
```bash
  oidc-provider:server_error:trace TypeError: ctx.response.get(...).forEach is not a function
  oidc-provider:server_error:trace     at sessionHandler (/home/soup/projects/work/agnes-emr-proxy/node_modules/oidc-provider/lib/shared/session.js:25:40)
  oidc-provider:server_error:trace     at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
```

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
{
    "claims": {
        "openid": ["sub"],
        "profile": ["name", "username", "userId", "orgId"]
    },
    "extraClientMetadata": {
        "properties": ["true_provider", "true_provider_org", "true_provider_facility", "devices"]
    },
    "features": {
        "devInteractions": false,
        "discovery": true,
        "registration": {
            "initialAccessToken": true,
            "policies": {}
        },
        "requestUri": {
            "requireRequestUriRegistration": false
        },
        "sessionManagement": true,
        "claimsParameter": true,
        "clientCredentials": true
    },
    "responseTypes": ["code", "token"]
}
```
I suspect that only sessionManagement is important here, but have included my full config for reference.

I am currently using development-only keystore, and I do not believe it would impact the behavior.

Clients are using dynamic registration with InitialAccessToken. Working with `openid-client` through `passport`. For metadata, I am only providing:

```js
{
    redirect_uris: ["https://localhost:5883/auth/doLogin"],
    true_provider: "pcc"
}
```

Steps to reproduce the behaviour:

1.  Log in through the OpenID provider
2.  Navigate to /session/end
3.  Encounter server_error

**Expected behaviour**
OIDC Provider should clear its cookies and/or session data and, if provided, redirect the user to the post_logout_redirect_uri.

**Environment:**
 - oidc-provider version: 5.5.1
 - node version: v10.13.0

**Additional context**
I discovered this issue when I borked my own code and wound up with an invalid user (my user code was incrementing its ID unintentionally; I rolled back the database and reapplied it, resulting in a user in my session with an invalid ID). I have verified that this issue exists also for valid users.

I suspect the issue may be related to a `koa` version difference, as `oidc-provider` seems to expect `ctx.response.get('set-cookie')` to return an array.

In an effort to work around this issue, I tried to use the session management feature to end my session, but found it refuses to work. I have tried both directly navigating to the endpoint, and redirecting my user through my relying party to the logout endpoint (e.g., using client.endSessionUrl); both result in this same error.

 - [X] the bug is happening on latest oidc-provider too.
 - [X] i have tried DEBUG (see readme.md) and can see the issue is with the provider and not my code.
 - [X] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [X] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs**
Please note that my session is pre-existing with respect to this run. I will rebuild my environment and create the situation again

```bash
NOTICE: a draft/experimental feature (sessionManagement) enabled, future updates to this feature will be released as MINOR releases
WARNING: configuration cookies.keys is missing, this option is critical to detect and ignore tampered cookies
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option lib/index.js:44:9
WARNING: a quick start development-only sign key is used, you are expected to provide your own during provider#initialize
body-parser deprecated undefined extended: provide extended option lib/auth/index.js:351:24
> NOTICE: default helper postLogoutRedirectUri called, you SHOULD change it in order to specify where to redirect the user after logout without post_logout_redirect_uri specified or validated.
NOTICE: default helper logoutSource called, you SHOULD change it in order to customize the look of the logout page.
  oidc-provider:server_error uuid=3b3056fa-7b33-4388-9c5f-9bba1ba6d2b2 path=/session/end method=GET error=TypeError: ctx.response.get(...).forEach is not a function at sessionHandler (/home/soup/projects/work/agnes-emr-proxy/node_modules/o
idc-provider/lib/shared/session.js:25:40) at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
  oidc-provider:server_error:trace TypeError: ctx.response.get(...).forEach is not a function
  oidc-provider:server_error:trace     at sessionHandler (/home/soup/projects/work/agnes-emr-proxy/node_modules/oidc-provider/lib/shared/session.js:25:40)
  oidc-provider:server_error:trace     at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
NOTICE: default helper renderError called, you SHOULD change it in order to customize the look of the error page.
```

**Comment by fauxsoup** [comment]
Hi @panva,

I assure you, I have version 5.5.1. I have just double-checked the package.json in node_modules; I also checked session.js and confirm that the forEach appears on line 34 in my node_modules too. I am running through `esm`; I wonder if that could change the line number being reported?

I am not mounting to a `koa` application; I'm mounting to `express@4.16.4`. I've been considering switching to `koa` though. However, since I'm not running `koa`, I don't have access to that method. I will try through node-debug and report my findings.

It is very possible that I'm misusing your session interfaces and creating a bad state. Perhaps calling `setProviderSession` with `remember = true`, but then `interactionFinished` with `remember = false`? I apologize in advance in case it is my fault.

**Comment by fauxsoup** [comment]
I can no longer reproduce this issue after changing my usage of `remember` in `setProviderSession` and `interactionFinished`, so I suspect it is very likely my fault. I will close this issue.
