### ISSUE TITLE
Failure to exchange AuthenticationCode to Token due too missing session.

### ISSUE THREAD

**Issue by milo526** [panva/node-oidc-provider#505]
While trying to exchange code from token (using https://openidconnect.net) an error is thrown:
```{ error: 'invalid_grant', error_description: 'grant request is invalid' }```
I believe this to be caused by the fact that the AuthorizationCode is not returned given:
``` not returning AuthorizationCode f5RTvZ_wpjjT-vZ9O-R8Dg-tyubKkpadNQtgv-KKmz6 because it is session bound and its related session was not found```

I'd like to request some help fixing this issue and getting up and running exchanging tokens.

My custom adapter is returning data from its `public async findByUid(uid: string): Promise<object | false>` function just before the error occurs. The function returns an object containing the following: 
```
{
  exp: 1564573335,
  iat: 1564572735,
  jti: 'f5RTvZ_wpjjT-vZ9O-R8Dg-tyubKkpadNQtgv-KKmz6',
  kind: 'AuthorizationCode',
  scope: 'openid email',
  claims: { rejected: [] },
  grantId: 'R_uAhqf78LJlJAclRgjRq',
  authTime: 1564571355,
  clientId: 'kbyuFDidLLm280LIwVFiazOqjO3ty8KH',
  accountId: 1,
  sessionUid: 'GAyCtD6EznlFq87KAJaUn',
  redirectUri: 'https://openidconnect.net/callback',
  expiresWithSession: true
}
```
Further research shows that [`lib/models/session.js:81`](https://github.com/panva/node-oidc-provider/blob/master/lib/models/session.js#L81) returns undefined due too an error. When modifying the source to show the error it prints
```
AssertionError [ERR_ASSERTION]: kind mismatch
    at new Class (.../node_modules/oidc-provider/lib/models/base_model.js:36:7)
    at new klass (.../node_modules/oidc-provider/lib/models/mixins/has_format.js:40:19)
    at new BaseModel (.../node_modules/oidc-provider/lib/models/base_model.js:100:3)
    at new Session (.../node_modules/oidc-provider/lib/models/session.js:51:7)
    at Function.findByUid (.../node_modules/oidc-provider/lib/models/session.js:86:16)
    at Function.find (.../node_modules/oidc-provider/lib/models/mixins/is_session_bound.js:20:21)
    at authorizationCodeHandler (.../node_modules/oidc-provider/lib/actions/grants/authorization_code.js:30:16)
    at callTokenHandler (.../node_modules/oidc-provider/lib/actions/token.js:86:7)
    at rejectDupes (.../node_modules/oidc-provider/lib/shared/reject_dupes.js:42:3)
    at implicitCheck (.../node_modules/oidc-provider/lib/actions/token.js:68:7)
    at allowedGrantTypeCheck (.../node_modules/oidc-provider/lib/actions/token.js:60:7)
    at supportedGrantTypeCheck (.../node_modules/oidc-provider/lib/actions/token.js:52:7)
    at stripGrantIrrelevantParams (.../node_modules/oidc-provider/lib/actions/token.js:38:7)
    at rejectDupes (.../node_modules/oidc-provider/lib/shared/reject_dupes.js:42:3)
    at auth (.../node_modules/oidc-provider/lib/shared/token_auth.js:218:9)
    at loadClient (.../node_modules/oidc-provider/lib/shared/load_client.js:13:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```
If been reading through a lot of issues, examples and the source code but I cannot for the live of me find out what is wrong with this format and what should be returned instead.

Lastly the full oidc-provider logs reads as follows
```
oidc-provider:authentication:accepted uid=sn09nUr2cP8KT3dSWSJE- Params { acr_values: undefined, claims_locales: undefined, client_id: 'kbyuFDidLLm280LIwVFiazOqjO3ty8KH', code_challenge: undefined, code_challenge_method: undefined, display: undefined, id_token_hint: undefined, login_hint: undefined, max_age: undefined, nonce: undefined, prompt: undefined, redirect_uri: 'https://openidconnect.net/callback', registration: undefined, request: undefined, request_uri: undefined, response_mode: 'query', response_type: 'code', scope: 'openid email', state: '8785885e77dc72d6dbb48ab3cb494033c88be834', ui_locales: undefined } +0ms
oidc-provider:authentication:success uid=sn09nUr2cP8KT3dSWSJE- { code: 'f5RTvZ_wpjjT-vZ9O-R8Dg-tyubKkpadNQtgv-KKmz6', state: '8785885e77dc72d6dbb48ab3cb494033c88be834' } +0ms
oidc-provider:token accepted uid=l6SqgAS8WdlJqlE8eXlbH Params { grant_type: 'authorization_code', code: 'f5RTvZ_wpjjT-vZ9O-R8Dg-tyubKkpadNQtgv-KKmz6', redirect_uri: 'https://openidconnect.net/callback', code_verifier: undefined, client_id: 'kbyuFDidLLm280LIwVFiazOqjO3ty8KH', client_assertion: undefined, client_assertion_type: undefined, client_secret: '60Op4HFM0I8ajz0WdiStAbziZVFQttXuxixHHs2R7r7CW8GR79lmmLqMhcSa' } +0ms
oidc-provider:mixin:is_session_bound not returning AuthorizationCode f5RTvZ_wpjjT-vZ9O-R8Dg-tyubKkpadNQtgv-KKmz6 because it is session bound and its related session was not found +0ms
oidc-provider:error uid=l6SqgAS8WdlJqlE8eXlbH path=/token method=POST error={ error: 'invalid_grant', error_description: 'grant request is invalid' } detail=authorization code not found +0ms
```

**Comment by panva** [comment]
> My custom adapter is returning data from its public async findByUid(uid: string): Promise<object | false> function just before the error occurs. The function returns an object containing the following:

This function is called on a Session model, not AuthorizationCode.

```
  /**
   *
   * Return previously stored instance of Session by its uid reference property. You only
   * need this method when issuing tokens bound to the end-user session. When a token is encountered
   * that is bound to the session it will attempt to load the session by the stored reference on the
   * token.
   *
   * @return {Promise} Promise fulfilled with the stored session object (when found and not
   * dropped yet due to expiration) or falsy value when not found anymore. Rejected with error
   * when encountered.
   * @param {string} uid the uid value associated with a Session instance
   *
   */
  async findByUid(uid) {

  }
```

You're supposed to return a Session matching the `uid` value, you're currently returning an AuthorizationCode (why?!) based on its `jti` instead.
