### ISSUE TITLE
help needed: our interaction session is not being found after login

### ISSUE THREAD

**Issue by msg-mmenendez** [panva/node-oidc-provider#545]
**Describe the bug**
When our client (An angular app using angular-oauth2-oidc library) starts is redirected to the provider correctly.
Then the login page apear, user introduce username & password and then user gets ´SessionNotFound: invalid_request´ error.

**Source code**

oidc.config.js
```js

module.exports = {
    // ... see the available options in Configuration options section
    features: {
        deviceFlow: { enabled: true },
        introspection: { enabled: true },
        revocation: { enabled: true },
        devInteractions: { enabled: false }
    },
    formats: {
        AccessToken: 'jwt',
    },
    clients: [{
        "client_id": "hub-web-app-dev",
        "grant_types": [
            "implicit"
        ],
        "client_secret": "supersecret",
        "redirect_uris": [
            "https://localhost:7000"
        ],
        "response_types": [
            "id_token"
        ],
        "revocation_endpoint_auth_method": "client_secret_basic",
        "introspection_endpoint_auth_method": "client_secret_basic"
    }
    ],
    adapter: DatabaseAdapter,
    cookies: {
        long: { signed: true, maxAge: (24 * 60 * 60) * 1000 }, // 1 day in ms
        short: { signed: true },
        keys: ['some secret key', 'and also the old rotated away some time ago', 'and one more'],
    },
    interactions: {
        url: async (ctx, interaction) => {
            return `/identity/interaction/${ctx.oidc.uid}`;
        }
    },
    jwks: {
        keys: [...]
    },
    ttl: {
        AccessToken: 60 * 60, // 1 hour in seconds
        AuthorizationCode: 10 * 60, // 10 minutes in seconds
        IdToken: 60 * 60, // 1 hour in seconds
        DeviceCode: 10 * 60, // 10 minutes in seconds
        RefreshToken: 24 * 60 * 60, // 1 day in seconds
    },
};
```

database.adapter.js
```js
const grantable = [
    'AccessToken',
    'AuthorizationCode',
    'RefreshToken',
];


class DatabaseAdapter {

    constructor(name) {
        this.name = name;
        this.repository = DI.em.getRepository(name);
        this.entity = Entities[name];
        if(this.entity == null || this.repository == null) throw new Error(`'${name}' is not mapped`);
    }

    async upsert(id, payload, expiresIn) {
        console.log('database.adapter: upsert', this.name, id, payload);
        const exist = await this.repository.findOne(id);
        if (exist) {
            exist.payload = payload;
            exist.expiresIn = expiresIn ? { expiresAt: new Date(Date.now() + (expiresIn * 1000)) } : undefined;
            return this.repository.flush();
        } else {
            const e = new this.entity.ref.entity();
            const entity = Object.assign(
                e,
                { data: payload },
                { id: id },
                payload.grantId ? { grantId: payload.grantId } : undefined,
                expiresIn ? { expiresAt: new Date(Date.now() + (expiresIn * 1000)) } : undefined
            );
            return await this.repository.persistAndFlush(entity)
        }
    }

    async find(id) {
        console.log('database.adapter: find', this.name, id);
        const e = await this.repository.findOne(id);
        if (e) {
            return e.consumedAt ? Object.assign({}, e.data, { consumed: true }) : e.data;
        }
        return undefined;
    }

    async consume(id) {
        console.log('database.adapter: consume', this.name, id);
        const e = await this.repository.find(id);
        if (e) {
            e.consumedAt = new Date();
            return await this.repository.persistAndFlush(e)
        }
        return undefined;
    }

    async destroy(id) {
        console.log('database.adapter: destroy', this.name, id);
        if (grantable.includes(this.name)) {
            const e = await this.repository.find(id);
            const promises = Object.keys(Entities)
                .map(e => Entities[e])
                .filter(e => e.grant === true)
                .map(e => e.schema.name)
                .map(name => this.destroyByGrantId(name, e.grantId));
            return await Promise.all(promises);
        }
        return await this.repository.remove(id, true)
    }

    async destroyByGrantId(name, grantId) {
        console.log('database.adapter: destroyByGrantId', name, grantId);
        const r = name ? DI.em.getRepository(name) : this.repository;
        return await r.remove({grantId: grantId}, true)
    }
}

module.exports = DatabaseAdapter;
```
main.js
```js
'use strict';

const path = require('path');
const express = require('express');
const helmet = require('helmet');
const {Provider} = require('oidc-provider');
const {MikroORM, RequestContext} = require('mikro-orm');
const {ORMConfig, ServerConfig, OIDCConfig} = require('./config');
const {DI} = require('./di');
const {InteractionController} = require('./controller');

const app = express();
app.enable('trust proxy');
app.set('view engine', 'ejs');
app.set('views', path.resolve(__dirname, 'views'));
let server;

(async () => {

    //INIT
    DI.orm = await MikroORM.init(ORMConfig);
    DI.em = DI.orm.em;
    DI.oidc = new Provider(`${ServerConfig.HOST}/identity`, OIDCConfig);
    DI.oidc.proxy = true;

    // MIDDLEWARE
    app.use(helmet());
    app.use(express.urlencoded({extended: true}));
    app.use(express.json());

    // ORM
    app.use((req, res, next) => {
        RequestContext.create(DI.orm.em, next);
        req.di = DI;
    });

    // INTERACTION
    app.use(`/identity/interaction`, InteractionController);

    // OIDC
    app.use('/identity', DI.oidc.callback);

    // NOT FOUND
    app.use((req, res) => res.status(404).json({message: 'No route found'}));

    server = app.listen(ServerConfig.PORT, () => {
        console.log(`Running at ${ServerConfig.HOST}/identity`);
    });

})().catch((err) => {
    if (server && server.listening) server.close();
    console.error(err);
    process.exitCode = 1;
});

```

interaction.controller.js
```js
const express = require('express');
const {DI} = require('../di');
const {ServerConfig} = require('../config');
const router = express.Router();

function setNoCache(req, res, next) {
    res.set('Pragma', 'no-cache');
    res.set('Cache-Control', 'no-cache, no-store');
    next();
}

router.get('/:uid', setNoCache, async (req, res, next) => {
    try {
        const details = await DI.oidc.interactionDetails(req, res);
        const { uid, prompt, params } = details;

        const client = await DI.oidc.Client.find(params.client_id);

        if (prompt.name === 'login') {
            return res.render('login', {
                client,
                uid,
                details: prompt.details,
                params,
                flash: undefined,
                prefix: ServerConfig.OIDC_PREFIX
            });
        }

        return res.render('interaction', {
            client,
            uid,
            details: prompt.details,
            params,
            prefix: ServerConfig.OIDC_PREFIX
        });
    } catch (err) {
        return next(err);
    }
});

router.post('/:uid/login', setNoCache, express.json(), async (req, res, next) => {
    try {
        const { uid, prompt, params } = await DI.oidc.interactionDetails(req, res);
        const client = await DI.oidc.Client.find(params.client_id);
        const accountId = req.body.username;

        const account = await DI.em.findOne('User', { $or: [
                { 'username': accountId },
                { 'email': accountId }
            ] });

        if (!account) {
            res.render('login', {
                client,
                uid,
                details: prompt.details,
                params: {
                    ...params,
                    login_hint: accountId,
                },
                flash: {
                    message: 'Invalid email or password.',
                    type: 'danger'
                },
            });
            return;
        }

        const result = {
            login: {
                account: account.id,
            },
        };

        await DI.oidc.interactionFinished(req, res, result, { mergeWithLastSubmission: false });
    } catch (err) {
        next(err);
    }
});

router.post('/:uid/confirm', setNoCache, async (req, res, next) => {
    try {
        const result = {
            consent: {
                // rejectedScopes: [], // < uncomment and add rejections here
                // rejectedClaims: [], // < uncomment and add rejections here
            },
        };
        await DI.oidc.interactionFinished(req, res, result, { mergeWithLastSubmission: true });
    } catch (err) {
        next(err);
    }
});

router.get('/:uid/abort', setNoCache, async (req, res, next) => {
    try {
        const result = {
            error: 'access_denied',
            error_description: 'End-User aborted interaction',
        };
        await DI.oidc.interactionFinished(req, res, result, { mergeWithLastSubmission: false });
    } catch (err) {
        next(err);
    }
});

module.exports = router;

```

**Environment:**
 - oidc-provider version: v6.12.4
 - node version: v12.11.1
 - mikro-orm version: 2.6.0 (To implement adapter)

**Logs**
```
database.adapter: find Session Gg50dX8v9yUvsex1O1EiK
database.adapter: find Client hub-web-app-dev
database.adapter: upsert Interaction zxhUXzLN0skpK65QygYsJ
  oidc-provider:authentication:interrupted uid=zxhUXzLN0skpK65QygYsJ interaction=Interaction { returnTo: 'https://localhost:7000/identity/auth/zxhUXzLN0skpK65QygYsJ', prompt: { name: 'login', reasons: [ 'no_session' ], details: { max_age: undefined, login_hint: undefined, id_token_hint: undefined } }, lastSubmission: undefined, uid: 'zxhUXzLN0skpK65QygYsJ', params: { client_id: 'hub-web-app-dev', nonce: 'mI5xkIGWsEGASZ3hjMlyjZ1J8s20hAlnL5vwxQOV', redirect_uri: 'https://localhost:7000', response_type: 'id_token', scope: 'openid', state: 'mI5xkIGWsEGASZ3hjMlyjZ1J8s20hAlnL5vwxQOV' }, signed: undefined, session: undefined, kind: 'Interaction', jti: 'zxhUXzLN0skpK65QygYsJ' } +0ms
database.adapter: upsert Session Gg50dX8v9yUvsex1O1EiK
database.adapter: find Interaction zxhUXzLN0skpK65QygYsJ
database.adapter: find Client hub-web-app-dev
database.adapter: find Interaction zxhUXzLN0skpK65QygYsJ
database.adapter: find Client hub-web-app-dev
database.adapter: find Interaction zxhUXzLN0skpK65QygYsJ
database.adapter: upsert Interaction zxhUXzLN0skpK65QygYsJ
database.adapter: find Session Gg50dX8v9yUvsex1O1EiK
database.adapter: find Interaction zxhUXzLN0skpK65QygYsJ
database.adapter: destroy Interaction zxhUXzLN0skpK65QygYsJ
database.adapter: find Client hub-web-app-dev
  oidc-provider:authentication:resumed uid=zxhUXzLN0skpK65QygYsJ undefined +0ms
database.adapter: upsert Interaction zxhUXzLN0skpK65QygYsJ
  oidc-provider:authentication:interrupted uid=zxhUXzLN0skpK65QygYsJ interaction=Interaction { returnTo: 'https://localhost:7000/identity/auth/zxhUXzLN0skpK65QygYsJ', prompt: { name: 'login', reasons: [ 'no_session' ], details: { max_age: undefined, login_hint: undefined, id_token_hint: undefined } }, lastSubmission: undefined, uid: 'zxhUXzLN0skpK65QygYsJ', params: { client_id: 'hub-web-app-dev', nonce: 'mI5xkIGWsEGASZ3hjMlyjZ1J8s20hAlnL5vwxQOV', redirect_uri: 'https://localhost:7000', response_type: 'id_token', scope: 'openid', state: 'mI5xkIGWsEGASZ3hjMlyjZ1J8s20hAlnL5vwxQOV' }, signed: [], session: undefined, kind: 'Interaction', jti: 'zxhUXzLN0skpK65QygYsJ' } +6m
database.adapter: destroy Session Gg50dX8v9yUvsex1O1EiK
database.adapter: upsert Session r7eiCIgNmGu3VepqABFzH
database.adapter: find Interaction zxhUXzLN0skpK65QygYsJ
SessionNotFound: invalid_request
    at Provider.getInteraction (/Users/mariomh/Projects/mm-hub-n/mm-hub-service-auth-n/node_modules/oidc-provider/lib/provider.js:55:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/mariomh/Projects/mm-hub-n/mm-hub-service-auth-n/src/controller/interaction.controller.js:14:25
```

**Comment by panva** [comment]
> When our client (An angular app using angular-oauth2-oidc library) starts is redirected to the provider correctly.
> Then the login page apear, user introduce username & password and then user gets ´SessionNotFound: invalid_request´ error.

Writing "as the user sees it" is not really helpful, can you provide a HAR of the exchange the browser does?
