### ISSUE TITLE
ctx.oidc.entity('AuthorizationCode', code) failed when Amazon Neptune adaptor is used

### ISSUE THREAD

**Issue by baechul** [panva/node-oidc-provider#607]
**Describe the bug**

When I use Amazon Neptune as an adaptor, I was able to get an auth code but failed in /ticket call. 

2019-12-10T17:36:33.395Z oidc-provider:server_error:trace ResponseError: Server error: {"requestId":"316a94d3-8a9c-45f1-9208-0c84c55f5d73","code":"UnsupportedOp
erationException","detailedMessage":"Unsupported property value type: java.util.LinkedHashMap"} (499)
    at Connection._handleMessage (/app/auth/node_modules/gremlin/lib/driver/connection.js:269:9)
    at WebSocket.<anonymous> (/app/auth/node_moket.emit (eventdules/gremlin/lib/driver/connection.js:129:43)
    at WebSocs.js:210:5)
    at Receiver._receiver.onmessage (/app/auth/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/app/auth/node_modules/ws/lib/Receiver.js:380:14)
    at Receiver.getData (/app/auth/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/app/auth/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/app/auth/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket.<anonymous> (/app/auth/node_modules/ws/lib/WebSocket.js:138:22)
    at TLSSocket.emit (events.js:210:5) 

This was triggered from 
ctx.oidc.entity('AuthorizationCode', code);
at https://github.com/panva/node-oidc-provider/blob/master/lib/actions/grants/authorization_code.js#L74

And the entity method has this line:
this.emit(`assign.${key.toLowerCase()}`, this.ctx, value);
at https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/oidc_context.js#L76

The emit will use the socket connection to the Amazon Neptune as in the stacktrace above but Neptune supports only either "single" cardinality for singe value or "set" for multiple values (reference: https://docs.aws.amazon.com/neptune/latest/userguide/access-graph-gremlin-differences.html)

I wonder if the value can be serialized/deserialized for neptune. 

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
// provider configuration

// keystore(s) - if they affect the behaviour

// client(s) configuration

```

Steps to reproduce the behaviour:

1.  
2.  
3.  

**Expected behaviour**

**Environment:**
 - oidc-provider version: [e.g. v4.3.0]
 - node version: [e.g. v8.9.0]

**Additional context**

 - [ ] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [ ] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**

**Comment by panva** [comment]
This report makes no sense to me, `OIDCContext.emit` does nothing with the `"adapter"` - storage - used within the context of this library. It merely [emits an event](https://nodejs.org/api/events.html#events_emitter_emit_eventname_args) within the Node.js runtime to its registered listeners.
