### ISSUE TITLE
The first login user cannot refresh tokenset after the second user logs in

### ISSUE THREAD

**Issue by theseventhflow** [panva/node-oidc-provider#669]
**Describe the bug**
Hi panva, I tried to implement oidc in my project. If I have only one user, the refresh function works perfectly. However, once the second user used another client to log in, the first user's tokenset cannot refresh anymore. 

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
// provider configuration
const oidc = new Provider(`http://localhost:${PORT}`, {
    adapter: RedisAdapter,
    clients: dataArray,
    jwks,
    issueRefreshToken:  async (ctx, client, code) => {
      return client.grantTypeAllowed('refresh_token');
    },
    // oidc-provider only looks up the accounts by their ID when it has to read the claims,
    // passing it our Account model method is sufficient, it should return a Promise that resolves
    // with an object with accountId property and a claims method.
    findAccount: Account.findAccount,

    // let's tell oidc-provider you also support the email scope, which will contain email and
    // email_verified claims
    claims: {
      //auth_time: 10 * 60 * 1000, //10mins,
      openid: ['sub', 'auth_time', 'client_id'],

      BB_App_login: ['email', 'email_verified'],
      BB_App_delete: ['delData', 'email'],
      BB_App_read: ['read', 'email']
    },
    clockTolerance: 0,
    cookies: {
      names: {
        session: "_session",
        interaction: "_interaction",
        resume: "_interaction_resume",
        state: "_state"
      },
      long: {
        signed: true,
        httpOnly: true, // not readable on javascipt client side
        maxAge: 10 * 60 * 10000, //14 days
        overwrite: true,
        sameSite: "none"
      },
      short: {

        signed: true,
        keys: true,
        httpOnly: true,
        maxAge: 10 * 60 * 1000, //10 mins
        overwrite: true,
        sameSite: "lax"
      },
      keys: ["hello", "wordl", "kaboom"] //can't change headers after they are sent to client // sends undefined errors
    },
    //time to live
    ttl: {
      AccessToken: 5,// switch to 5 s for test
      AuthorizationCode: 15,
      ClientCredentials: 15,
      DeviceCode: 15,
      IdToken: 15,
      // RefreshToken:10
      RefreshToken: 1 * 24 * 60 * 60,//one day

    },
    // let's tell oidc-provider where our own interactions will be
    // setting a nested route is just good practice so that users
    // don't run into weird issues with multiple interactions open
    // at a time.
    interactionUrl(ctx) {
      return `/interaction/${ctx.oidc.uid}`;
    },
    features: {
      // disable the packaged interactions
      devInteractions: { enabled: false },

      introspection: { enabled: true },
      revocation: { enabled: true },
    },
  });

// client(s) configuration

```app.get('/refresh/:client_id', async  (req,res) => {
    const currentID = req.params.client_id
    const clientData = clientMap.get(currentID)
    console.log({oldTokenSet:clientData.tokenSet,clientid:currentID})
    clientData.refresh(clientData.tokenSet).then(newTokenSet => {
        console.log({newTokenSet:newTokenSet})
        clientData.tokenSet = newTokenSet
        clientMap.set(currentID,clientData)
        res.send(clientData)
    }).catch(error => {
        console.log("this is an error!")
        console.log(error)
        res.send(clientData)
    })
})

Steps to reproduce the behaviour:

1.  first user logged in
2.  second user logged in
3.  refresh the first user's tokenset

**Expected behaviour**
The tokenset of the first user will not be refreshed
OPError: invalid_grant (grant request is invalid)
    at processResponse (/home/bgu/build/dynamicalerts/node_modules/openid-client/lib/helpers/process_response.js:39:13)
    at Client.grant (/home/bgu/build/dynamicalerts/node_modules/openid-client/lib/client.js:1075:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Client.refresh (/home/bgu/build/dynamicalerts/node_modules/openid-client/lib/client.js:879:22) {
  error: 'invalid_grant',
  error_description: 'grant request is invalid'
}

**Environment:**
 - oidc-provider version: 6.12.1
 - node version: 12.13.1

**Additional context**
Add any other context about the problem here.

 - [ ] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [ ] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**
<!-- run the server with DEBUG=oidc-provider:* and paste the formatted logs or a gist link here -->

**Comment by theseventhflow** [comment]
Could you give me any suggestions?Thank you!

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#expireswithsession

**Comment by panva** [comment]
Basically, since the token family is bound to the session (the helper above resolves to true for you without offline_access) and you're logging out the first user to log in the second one, the family is invalidated. Test in different browsers or an anonymous window.

**Comment by theseventhflow** [comment]
Oh thank you so much! It works when users use different browsers.
