### ISSUE TITLE
v6.21.1 breaks authorization code flow

### ISSUE THREAD

**Issue by baronnoraz** [panva/node-oidc-provider#671]
**Describe the bug**
In versions of `oidc-provider` prior to `6.21.1` our web app login works correctly using the authorization code flow.  `6.21.0` was the last version that worked.

**To Reproduce**
Provider configuration
```js
const {
  interactionPolicy: { Prompt, Check, base }
} = require('oidc-provider');

const jwks = require('./jwks.json');

const basePolicy = base();
const prompt = basePolicy.get('consent');
prompt.checks.remove('native_client_prompt');
prompt.checks.remove('consent_prompt');

const oidcConfiguration = {
  clients: [
    {
      client_id: `${process.env.CLIENT_ID}`,
      client_secret: `${process.env.CLIENT_SECRET}`,
      redirect_uris: [`${process.env.REDIRECT_URL}`],
      response_types: ['id_token', 'code'],
      grant_types: [
        'password',
        'implicit',
        'refresh_token',
        'authorization_code'
      ],
      application_type: 'native'
    },
    {
      client_id: `${process.env.ADMIN_CLIENT_ID}`,
      client_secret: `${process.env.ADMIN_CLIENT_SECRET}`,
      redirect_uris: [`${process.env.ADMIN_REDIRECT_URL}`,`${process.env.ADMIN_SILENT_RENEW_URL}`],
      grant_types: ['refresh_token', 'authorization_code', 'password'],
      application_type: 'web',
      token_endpoint_auth_method: 'client_secret_post',
      post_logout_redirect_uris: [
        `${process.env.ADMIN_POST_LOGOUT_REDIRECT_URL}`
      ]
    }
  ],
  conformIdTokenClaims: false,
  extraAccessTokenClaims: async (ctx, token) => {

    if (token.clientId === `${process.env.ADMIN_CLIENT_ID}`) {
      return await AdminUserDb.getAdminUser(token.accountId);
    }

    const studyId = getClientStudyId(token.clientId);
    const authInfo: UserAuthInfo = await UserDb.getUserAuthInfo(
      token.accountId,
      studyId
    );
    return {
      participant_id: authInfo.participantId
    };
  },
  cookies: {
    long: { signed: true, maxAge: 1 * 24 * 60 * 60 * 1000 }, // 1 day in ms
    short: { signed: true },
    keys: [
      'Km`c>J^rM85<A0|{M}(&Oz.j,FgfWj',
      'qb-V;O{YiT.y0<]{p0Yl[@RkoI7tx+',
      '8n4zwD/ST%}bWNK|-[r69B&L=]lNm1'
    ]
  },
  claims: {
    openid: ['sub'],
    profile: [
      'username',
      'participant_id'
    ]
  },
  dynamicScopes: [/.*/],
  features: {
    // disable the packaged interactions
    devInteractions: { enabled: false },

    encryption: { enabled: true },
    introspection: { enabled: true },
    revocation: { enabled: true },
    claimsParameter: { enabled: true }
  },
  formats: {
    AccessToken: 'jwt'
  },
  jwks,
  interactionUrl(ctx) {
    return `/interaction/${ctx.oidc.uid}`;
  },
  ttl: {
    AccessToken: 1 * 60 * 5, // 1 hour in seconds
    AuthorizationCode: 10 * 60, // 10 minutes in seconds
    IdToken: 1 * 60 * 60, // 1 hour in seconds
    DeviceCode: 10 * 60, // 10 minutes in seconds
    RefreshToken: 1 * 24 * 60 * 60 // 1 day in seconds
  },
  findAccount: null,
  interactions: {
    policy: basePolicy
  }
  // userStore: new WebStorageStateStore({ store: window.localStorage })
};

export default oidcConfiguration;

```

Client configuration
```js
const userManagerConfig = {
  client_id: `${process.env.CLIENT_ID}`,
  client_secret: `${process.env.CLIENT_SECRET}`,
  redirect_uri: `${url}/auth/callback`,
  authority: `${url}/oidc`,
  response_type: 'code',
  scope: 'openid profile email api',
  triggerAuthFlow: true,
  post_logout_redirect_uri: `${url}/auth/logout`,
  silent_redirect_uri: `${url}/auth/renew`,
  automaticSilentRenew: true,
  includeIdTokenInSilentRenew: true,
  silentRequestTimeout: 30000,
  revokeAccessTokenOnSignout: true
};
```

Steps to reproduce the behaviour:

1. Click Login button on my site:

```
GET
http://localhost:8080/oidc/auth?client_id=admin&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Fauth%2Fcallback&response_type=code&scope=openid%20profile%20email%20api&state=7d1e48f247c741a1b467deefbfbdbe2a&code_challenge=jnm-TMwLdZDcJrQD0mea4vJWlZQBi-acy4u2kj-XnGs&code_challenge_method=S256&response_mode=query
```

2.  Presented with login screen from oidc-provider  
3.  Enter login credentials and click "Sign-in"

```
POST
http://localhost:8080/interaction/gpu7LDcguOIZZpoxkeWnv/login
username: nbuckner
password: secret
```

4. I see the auth callback return with an error and return to my screen with the login button

```
GET
http://localhost:3001/auth/callback?error=server_error&error_description=oops!%20something%20went%20wrong&state=7d1e48f247c741a1b467deefbfbdbe2a
error: server_error
error_description: oops! something went wrong
state: 7d1e48f247c741a1b467deefbfbdbe2a
```

5. I look at the server log and see an error thrown within `oidc-provider`

```
TypeError: account must be a non-empty string, got: number
    at Object.set (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/shared/session.js:17:19)
    at baseAssignValue (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_baseAssignValue.js:21:17)
    at assignValue (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_assignValue.js:24:5)
    at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/assign.js:53:7
    at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/_createAssigner.js:30:9
    at apply (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_apply.js:15:25)
    at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/_overRest.js:32:12
    at Proxy.loginAccount (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/models/session.js:337:7)
    at resumeAction (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/actions/authorization/resume.js:110:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Expected behaviour**
In version `6.21.0` and prior the authentication succeeded and I was redirected to my website's landing page.

**Environment:**
 - oidc-provider version: 6.21.1+
 - node version: v12.13.1

**Additional context**

 - [YES] the bug is happening on latest oidc-provider too.
 - [YES] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [YES] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [YES] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**
```
  oidc-provider:authentication:interrupted uid=v6UR95H6zwQu0a0KYvNRo interaction=Interaction { returnTo: 'http://localhost:8080/oidc/auth/v6UR95H6zwQu0a0KYvNRo', prompt: { name: 'login', reasons: [ 'no_session' ], details: { max_age: undefined, login_hint: undefined, id_token_hint: undefined } }, lastSubmission: undefined, uid: 'v6UR95H6zwQu0a0KYvNRo', params: { client_id: 'hmp-admin', code_challenge: 'xlJtzp_B7apLO2U-wICH4NEC4HzOM5gsrqUqBMvScFg', code_challenge_method: 'S256', redirect_uri: 'http://localhost:3001/auth/callback', response_mode: 'query', response_type: 'code', scope: 'openid profile email api', state: 'acffac21e6f2439f865f55d3318f9926' }, signed: undefined, session: undefined, kind: 'Interaction', jti: 'v6UR95H6zwQu0a0KYvNRo', exp: 1583773272 } +0ms
TypeError: account must be a non-empty string, got: number
    at Object.set (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/shared/session.js:17:19)
    at baseAssignValue (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_baseAssignValue.js:21:17)
    at assignValue (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_assignValue.js:24:5)
    at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/assign.js:53:7
    at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/_createAssigner.js:30:9
    at apply (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_apply.js:15:25)
    at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/_overRest.js:32:12
    at Proxy.loginAccount (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/models/session.js:337:7)
    at resumeAction (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/actions/authorization/resume.js:110:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  oidc-provider:server_error uid=v6UR95H6zwQu0a0KYvNRo path=/auth/v6UR95H6zwQu0a0KYvNRo method=GET error=TypeError: account must be a non-empty string, got: number at Object.set (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/shared/session.js:17:19) at baseAssignValue (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_baseAssignValue.js:21:17) at assignValue (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_assignValue.js:24:5) at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/assign.js:53:7 at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/_createAssigner.js:30:9 at apply (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_apply.js:15:25) at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/_overRest.js:32:12 at Proxy.loginAccount (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/models/session.js:337:7) at resumeAction (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/actions/authorization/resume.js:110:13)     at processTicksAndRejections (internal/process/task_queues.js:93:5) +0ms
  oidc-provider:server_error:trace TypeError: account must be a non-empty string, got: number
  oidc-provider:server_error:trace     at Object.set (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/shared/session.js:17:19)
  oidc-provider:server_error:trace     at baseAssignValue (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_baseAssignValue.js:21:17)
  oidc-provider:server_error:trace     at assignValue (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_assignValue.js:24:5)
  oidc-provider:server_error:trace     at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/assign.js:53:7
  oidc-provider:server_error:trace     at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/_createAssigner.js:30:9
  oidc-provider:server_error:trace     at apply (/Users/nbuckner/git/hmp-server/server/node_modules/lodash/_apply.js:15:25)
  oidc-provider:server_error:trace     at /Users/nbuckner/git/hmp-server/server/node_modules/lodash/_overRest.js:32:12
  oidc-provider:server_error:trace     at Proxy.loginAccount (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/models/session.js:337:7)
  oidc-provider:server_error:trace     at resumeAction (/Users/nbuckner/git/hmp-server/server/node_modules/oidc-provider/lib/actions/authorization/resume.js:110:13)
  oidc-provider:server_error:trace     at processTicksAndRejections (internal/process/task_queues.js:93:5) +0ms
```

**Comment by panva** [comment]
As per the Core specification, all subject values are to be strings, so this was nothing more than a bug fix. #650 and #655 are all issues related to that topic.

I didn't realize numbers got through before this fix but the current state is the  only intended and correct one.

**Comment by baronnoraz** [comment]
Thanks for the quick response.  To be sure, you're saying that the `token.accountId` should be a string and not a numeric value?

**Comment by panva** [comment]
yes, absolutely.
