### ISSUE TITLE
post_logout_redirect_uris not validated for dynamically configured clients

### ISSUE THREAD

**Issue by ctavan** [panva/node-oidc-provider#824]
**Describe the bug**
When using custom dynamic client registration (by providing appropriate configs through the adapter `find()` method), it currently seems to be possible to configure a client with `post_logout_redirect_uris: undefined,`.

If subsequently the end_session_endpoint is called, the following error is thrown:

```
TypeError: Cannot read property 'includes' of undefined
    at Client.postLogoutRedirectUriAllowed (/app/node_modules/oidc-provider/lib/models/client.js:502:42)
    at endSessionChecks (/app/node_modules/oidc-provider/lib/actions/end_session.js:58:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async parseBodyIfPost (/app/node_modules/oidc-provider/lib/shared/conditional_body.js:7:5)
    at async sessionHandler (/app/node_modules/oidc-provider/lib/shared/session.js:29:5)
    at async noCache (/app/node_modules/oidc-provider/lib/shared/no_cache.js:4:3)
    at async errorHandler (/app/node_modules/oidc-provider/lib/shared/error_handler.js:23:7)
    at async ensureSessionSave (/app/node_modules/oidc-provider/lib/helpers/initialize_app.js:51:7)
    at async contextEnsureOidc (/app/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5)
    at async /app/node_modules/oidc-provider/lib/helpers/initialize_app.js:246:5
    at async errorHandler (/app/node_modules/oidc-provider/lib/shared/error_handler.js:23:7)
```

**To Reproduce**
See this commit for a reproduction: https://github.com/ctavan/node-oidc-provider/commit/dee507f15c5968cc6b7c8b4f7f9a92099b9e9b1d

Steps to reproduce the behaviour:

1.  `cd example && node standalone.js`
2. Open example.html and click the sign-in link, sign in.
3. Copy the CODE from the callback URL and issue: `cd example && ./example-curl CODE`
4. Copy the `id_token` and follow the sign-out link from example.html, inserting the `id_token`

**Expected behaviour**
Client configuration should be validated and appropriate errors should be shown. This is the case when using static `clients` config.

**Environment:**
 - oidc-provider version: 6.29.7
 - node version: v15.2.1

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**

**Comment by panva** [comment]
@ctavan thank you for finding out, this is now fixed in [v6.29.8](https://github.com/panva/node-oidc-provider/releases/tag/v6.29.8).

Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.

**Comment by panva** [comment]
Also, great job on the reproduction, it has helped me a great deal.

**Comment by ctavan** [comment]
Thank you for the quick fix!
