### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to  the client

### ISSUE THREAD

**Issue by linqFR** [panva/node-oidc-provider#929]
**Describe the bug**

Post to /auth (with and without devInteractions:{enabled:true})
```
Request Headers
  User-Agent: PostmanRuntime/7.26.10
  Accept: */*
  Cache-Control: no-cache
  Postman-Token: e1259231-2a7c-4f24-a3fb-7aa06f0b6c1c
  Host: localhost:8000
  Accept-Encoding: gzip, deflate, br
  Connection: keep-alive
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 85
Request Body
  client_id: "testpwd"
  client_secret: "test"
  grant_type: "authorization_code"
  response_type: "code"
```
**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
// provider configuration
 {
	adapter,
	jwks:JWTstore,
	findAccount:account.findAccount,
	dPop:{
		// Browser-focused implementation of OAuth 2.0 Demonstration
		// of Proof-of-Possession at the Application Layer - draft-ietf-oauth-dpop-00.
		// needed for browser directly exchanging with oidc server => enabled : true
		// enabled:false,
		enabled:true,
		iatTolerance:60
	},
	// clientDefaults:{},
	// formats:{
	// 	AccessToken:'jwt'
	// },
	clients:[
		{
			client_name:'testCC',
			client_id: 'testcc',
			client_secret: 'test',
			grant_types: [
				// all possible grand_types
				'client_credentials',
				'authorization_code',
				'refresh_token',
				'urn:ietf:params:oauth:grant-type:device_code'
			],
			// "token_endpoint_auth_method": "client_secret_post",
			"id_token_signed_response_alg": "HS256",
			redirect_uris: ['http://xxx.io'],
			scopes:['cctest'],
			// subject_type:'pairwise'
			// response_types: ['code','id_token']
		},
		{
			client_name:'testPWD',
			client_id: 'testpwd',
			client_secret: 'test',
			grant_types: [
				// all possible grand_types
				// 'client_credentials',
				'authorization_code',
				'refresh_token',
				'urn:ietf:params:oauth:grant-type:device_code'
			],
			"token_endpoint_auth_method": "client_secret_post",
			"id_token_signed_response_alg": "HS256",
			redirect_uris: ['http://xxx.io'],
			scopes:['pwdtest'],
			// subject_type:'pairwise'
			// response_types: ['code','id_token']
		}
	],
	scopes:['openid','offline_access','cctest','pwdtest'],
	subjectTypes:['public','pairwise'],
	cookies:{
		long: {
			signed: true,
			maxAge: 24 * 60 * 60e3 // 1 day
		},
		short: {
			signed: true
		},
		keys: [
			'some secret key',
			'and also the old rotated away some time ago',
			'and one more'
		],
	},
	claims: {
		//openid claims
		address: ['address'],
		email: ['email', 'email_verified'],
		phone: ['phone_number', 'phone_number_verified'],
		profile: ['birthdate', 'family_name', 'gender', 'given_name', 'locale', 'middle_name', 'name','nickname', 'picture', 'preferred_username', 'profile', 'updated_at', 'website', 'zoneinfo'],
	},
	features:{
		clientCredentials:{enabled:true},

		// devInteractions:{enabled:true}, // change for production

		encryption:{enabled:true},
		// ietfJWTAccessTokenProfile:{enabled:true},
		introspection:{
			enabled: true,
		// 	allowedPolicy: [
		// 		async function (ctx, client, token) {
		// 			if (client.introspectionEndpointAuthMethod === 'none' && token.clientId !== ctx.oidc.client.clientId) {
		// 				return false
		// 		  	}
		// 			return true;
		// 		}
		// 	]
		},
		deviceFlow:{enabled:true},
		revocation:{enabled:true}, // Enables Token Revocation
		registration:{
			enabled:true,
			idFactory,
			secretFactory:idFactory,
			initialAccessToken:true
		},
		registrationManagement:{
			enabled:true,
			rotateRegistrationAccessToken:true
		}
	},
	ttl: {
		AccessToken: 1 * 60 * 60, // 1 hour in seconds
		AuthorizationCode: 10 * 60, // 10 minutes in seconds
		IdToken: 1 * 60 * 60, // 1 hour in seconds
		DeviceCode: 10 * 60, // 10 minutes in seconds
		// RefreshToken: 1 * 24 * 60 * 60, // 1 day in seconds
		RefreshToken: function RefreshTokenTTL(ctx, token, client) {
			//default implementation
			if (
				ctx && ctx.oidc.entities.RotatedRefreshToken
				&& client.applicationType === 'web'
				&& client.tokenEndpointAuthMethod === 'none'
				&& !token.isSenderConstrained()
			) {
				// Non-Sender Constrained SPA RefreshTokens do not have infinite expiration through rotation
				return ctx.oidc.entities.RotatedRefreshToken.remainingTTL;
			}
			return 14 * 24 * 60 * 60; // 14 days in seconds
		}
	}
}

```

Steps to reproduce the behaviour:

1.  start server oidc (provider.listen...) with or without devInteractions:{enabled:true} 
2.  post/auth payload

**Expected behaviour**
no sending of headers twice

**Environment:**
 - oidc-provider version: 6.31.1

**Additional context**

 - [X] the bug is happening on latest oidc-provider too.
 - [X] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [ ] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.

**Logs**

```
oidc-provider:server_error uid=sWh9wpqXA81QdXHupzrp7 path=/auth method=POST error=Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
     at ServerResponse.setHeader (_http_outgoing.js:558:11) at Cookies.set (xxx\node_modules\cookies\index.js:116:13)
     at Object.set (xxx\node_modules\oidc-provider\lib\helpers\samesite_handler.js:12:13)
     at interactions (xxx\node_modules\oidc-provider\lib\actions\authorization\interactions.js:118:13)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at async selectiveBody (xxx\node_modules\oidc-provider\lib\shared\selective_body.js:49:5)
     at async parseBodyIfPost (xxx\node_modules\oidc-provider\lib\shared\conditional_body.js:5:5)
     at async sessionHandler (xxx\node_modules\oidc-provider\lib\shared\session.js:29:5)
     at async noCache (xxx\node_modules\oidc-provider\lib\shared\no_cache.js:4:3)
     at async authorizationErrorHandler (xxx\node_modules\oidc-provider\lib\shared\authorization_error_handler.js:55:7)
{ code: 'ERR_HTTP_HEADERS_SENT' } +0ms
  oidc-provider:server_error:trace Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
  oidc-provider:server_error:trace     at ServerResponse.setHeader (_http_outgoing.js:558:11)
  oidc-provider:server_error:trace     at Cookies.set (xxx\node_modules\cookies\index.js:116:13)
  oidc-provider:server_error:trace     at Object.set (xxx\node_modules\oidc-provider\lib\helpers\samesite_handler.js:12:13)
  oidc-provider:server_error:trace     at interactions (xxx\node_modules\oidc-rovider\lib\actions\authorization\interactions.js:118:13)
  oidc-provider:server_error:trace     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  oidc-provider:server_error:trace     at async selectiveBody (xxx\node_modules\oidc-provider\lib\shared\selective_body.js:49:5)     
  oidc-provider:server_error:trace     at async parseBodyIfPost (xxx\node_modules\oidc-provider\lib\shared\conditional_body.js:5:5)  
  oidc-provider:server_error:trace     at async sessionHandler (xxx\node_modules\oidc-provider\lib\shared\session.js:29:5)
  oidc-provider:server_error:trace     at async noCache (xxx\node_modules\oidc-provider\lib\shared\no_cache.js:4:3)
  oidc-provider:server_error:trace     at async authorizationErrorHandler (xxx\node_modules\oidc-provider\lib\shared\authorization_error_handler.js:55:7) +0ms
  oidc-provider:error uid=sWh9wpqXA81QdXHupzrp7 path=/auth method=POST error={ error: 'invalid_request', error_description: 'unrecognized route or not allowed method (POST on /auth)' } detail=undefined +0ms
```

**Comment by panva** [comment]
I cannot reproduce this, nor #927.

I suspect the issue may be related e.g. to if and how you mount your provider instance to an existing application? Dunno.

```
❯ curl -iX POST https://op.panva.cz/token -d ''   
HTTP/2 400 
cache-control: no-cache, no-store
content-security-policy: default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
content-type: application/json; charset=utf-8
date: Thu, 04 Mar 2021 11:19:31 GMT
expect-ct: max-age=0
pragma: no-cache
referrer-policy: no-referrer
server: Caddy
server: Cowboy
strict-transport-security: max-age=15552000; includeSubDomains
vary: Origin
via: 1.1 vegur
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-xss-protection: 0
content-length: 93

{"error":"invalid_request","error_description":"no client authentication mechanism provided"}
```

```
curl -iX POST https://op.panva.cz/auth -d '' 
HTTP/2 400 
cache-control: no-cache, no-store
content-security-policy: default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
content-type: text/html; charset=utf-8
date: Thu, 04 Mar 2021 11:19:45 GMT
expect-ct: max-age=0
pragma: no-cache
referrer-policy: no-referrer
server: Caddy
server: Cowboy
strict-transport-security: max-age=15552000; includeSubDomains
via: 1.1 vegur
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-xss-protection: 0
content-length: 1080

<!DOCTYPE html>
    <head>
      <meta charset="utf-8">
      <title>oops! something went wrong</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      <style>
        @import url(https://fonts.googleapis.com/css?family=Roboto:400,100);h1{font-weight:100;text-align:center;font-size:2.3em}body{font-family:Roboto,sans-serif;margin-top:25px;margin-bottom:25px}.container{padding:0 40px 10px;width:274px;background-color:#F7F7F7;margin:0 auto 10px;border-radius:2px;box-shadow:0 2px 2px rgba(0,0,0,.3);overflow:hidden}pre{white-space:pre-wrap;white-space:-moz-pre-wrap;white-space:-pre-wrap;white-space:-o-pre-wrap;word-wrap:break-word;margin:0 0 0 1em;text-indent:-1em}
      </style>
    </head>
    <body>
      <div class="container">
        <h1>oops! something went wrong</h1>
        <pre><strong>error</strong>: invalid_request</pre><pre><strong>error_description</strong>: missing required parameter &#39;client_id&#39;</pre>
      </div>
    </body>
    </html>
```

**Comment by linqFR** [comment]
i m using it as a standalone server (no koa, no express)
```
import {Provider} from 'oidc-provider'

/*****************************************************************************
 		config
*****************************************************************************/
const {PROTOCOL='http',HOST='localhost',PORT=8000}=process.env

import config from './config/index.js'

/*****************************************************************************
 		init
*****************************************************************************/

const server = new Provider(`${PROTOCOL}://${HOST}:${PORT}`,config)

server.use(helmet())
server.use(morgan('dev'))
(async ()=>{

	server.use(async (ctx,next)=>{
		logger.info('server in use')
		// console.log('before',ctx,next)
		next()
	})

	server.listen(PORT,(...a)=>{
		logger.start(`api server started: ${PROTOCOL}://${HOST}:${PORT}`,...a)
	})

})().catch(err=>{
	if(server && server.listening) server.close()
	logger.fatal(`oidc server died`,err)
	console.log(`oidc server died`,err)
	process.exitCode = -1
})
```

**Comment by panva** [comment]
So it's the same as my deployment shown above. I cannot reproduce.

**Comment by linqFR** [comment]
just that i have no interactions html pages implemented

**Comment by linqFR** [comment]
code is [here - https://github.com/linqFR/OIDC-try](https://github.com/linqFR/OIDC-try)

**Comment by panva** [comment]
Please prepare a proper reproduction package. Either a public repo or a gist, with package.json, package-lock.json, clear instructions on how to start your project on localhost, etc. But most importantly proper reproduction steps starting with step 1 - clear your cookies for localhost, ...

**Comment by linqFR** [comment]
repo is public now
just download, install `npm i` and `npm run dev` (node 14.16.0)
then `post /auth `
`Content-Type: application/x-www-form-urlencoded`
body : 
```
client_id: "testpwd"
client_secret: "test"
grant_type: "authorization_code"
response_type: "code"
redirect_uris: "http://xxx.io"
```

**Comment by panva** [comment]
```diff
	server.use(async (ctx,next)=>{
		logger.info('server in use')
		// console.log('before',ctx,next)
-		next()
+		return next()
	})
```

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library this and the previous support was of help to you. Doing so will ensure you'll be getting any future support.

**Comment by linqFR** [comment]
actually this is more like this, no?

but thank you ! i m more used to express than koa and now i see the difference with 'next' usage !
```
	server.use(async (ctx,next)=>{
		logger.info('server in use')
		// console.log('before',ctx,next)
-		next()
+		await next()
	})
```

**Comment by panva** [comment]
It's irrelevant if you await the promise or return it in an async function. If you're more comfortable using express, do so. This issue could've easily be avoided if you didn't dive into waters you're not comfortable with. I kindly ask that before resolving to opening any further issues/discussions you check the basics first.

**Comment by linqFR** [comment]
Sorry to have disturbed you for so few ! my bad!

Not diving into unknown zones is the best way to never be comfortable with new things,
and for sure, oidc/oauth2 is quite cryptic for newbies, your module is quite the only that makes a bit senses !

thanks again
